import type { FormatConfig } from 'oxfmt'

import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { format } from 'oxfmt'

export const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..')

let oxfmtConfig: FormatConfig | undefined

export function createGeneratedHeader(scriptPath: string, extraLines: string[] = []) {
  return [`// This file is generated by \`${scriptPath}\`.`, '// Do not edit this file manually.', ...extraLines].join(
    '\n',
  )
}

export function resolveFromRoot(filePath: string) {
  return path.resolve(ROOT_DIR, filePath)
}

export async function getOxfmtConfig(): Promise<FormatConfig> {
  if (oxfmtConfig) return oxfmtConfig

  const configUrl = pathToFileURL(resolveFromRoot('oxfmt.config.ts')).href
  const mod = (await import(configUrl)) as { default: FormatConfig }

  oxfmtConfig = mod.default
  return oxfmtConfig
}

export async function formatSourceForFile(filePath: string, source: string) {
  const absoluteTargetPath = resolveFromRoot(filePath)
  const config = await getOxfmtConfig()
  const result = await format(absoluteTargetPath, source, config)
  return result.code
}
