name: Setup
description: Setup pnpm, Node.js

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/setup@v2
      with:
        runtime: node@24
        cache: true

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build packages
      shell: bash
      run: pnpm build
