export * from './base'
export * from './configs/nextjs'
export * from './configs/playwright'
export * from './configs/react'
export * from './configs/tailwindcss'
export * from './configs/vitest'
export * from './globs'
export type { OxlintConfig, OxlintOverride } from 'oxlint'
