import type { Overrides } from './types'

export const react: Overrides = [
  {
    files: ['**/*.{ts,tsx}'],
    jsPlugins: [
      'eslint-plugin-react-x',
      'eslint-plugin-react-rsc',
      'eslint-plugin-react-dom',
      'eslint-plugin-react-web-api',
      'eslint-plugin-react-naming-convention',
    ],
    rules: {
      'react-x/jsx-dollar': 'error',
      'react-x/jsx-key-before-spread': 'error',
      'react-x/jsx-no-comment-textnodes': 'error',
      'react-x/jsx-shorthand-boolean': 'error',
      'react-x/jsx-shorthand-fragment': 'error',
      'react-x/component-hook-factories': 'error',
      'react-x/error-boundaries': 'error',
      'react-x/exhaustive-deps': 'error',
      'react-x/immutability': 'error',
      'react-x/no-access-state-in-setstate': 'error',
      'react-x/no-array-index-key': 'error',
      'react-x/no-children-count': 'error',
      'react-x/no-children-for-each': 'error',
      'react-x/no-children-map': 'error',
      'react-x/no-children-only': 'error',
      'react-x/no-children-prop': 'error',
      'react-x/no-children-to-array': 'error',
      'react-x/no-class-component': 'error',
      'react-x/no-clone-element': 'error',
      'react-x/no-component-will-mount': 'error',
      'react-x/no-component-will-receive-props': 'error',
      'react-x/no-component-will-update': 'error',
      'react-x/no-context-provider': 'error',
      'react-x/no-create-ref': 'error',
      'react-x/no-direct-mutation-state': 'error',
      'react-x/no-duplicate-key': 'error',
      'react-x/no-forward-ref': 'error',
      'react-x/no-implicit-children': 'error',
      'react-x/no-implicit-key': 'error',
      'react-x/no-implicit-ref': 'error',
      'react-x/no-leaked-conditional-rendering': 'error',
      'react-x/no-missing-component-display-name': 'error',
      'react-x/no-missing-context-display-name': 'error',
      'react-x/no-missing-key': 'error',
      'react-x/no-misused-capture-owner-stack': 'error',
      'react-x/no-nested-component-definitions': 'error',
      'react-x/no-nested-lazy-component-declarations': 'error',
      'react-x/no-redundant-should-component-update': 'error',
      'react-x/no-set-state-in-component-did-mount': 'error',
      'react-x/no-set-state-in-component-did-update': 'error',
      'react-x/no-set-state-in-component-will-update': 'error',
      'react-x/no-unnecessary-use-callback': 'error',
      'react-x/no-unnecessary-use-memo': 'error',
      'react-x/no-unnecessary-use-prefix': 'error',
      'react-x/no-unsafe-component-will-mount': 'error',
      'react-x/no-unsafe-component-will-receive-props': 'error',
      'react-x/no-unsafe-component-will-update': 'error',
      'react-x/no-unstable-context-value': 'error',
      'react-x/no-unstable-default-props': 'error',
      'react-x/no-unused-class-component-members': 'error',
      'react-x/no-unused-props': 'error',
      'react-x/no-unused-state': 'error',
      'react-x/no-use-context': 'error',
      'react-x/no-useless-fragment': 'error',
      'react-x/prefer-destructuring-assignment': 'error',
      'react-x/prefer-namespace-import': 'error',
      'react-x/purity': 'error',
      'react-x/refs': 'error',
      'react-x/rules-of-hooks': 'error',
      'react-x/set-state-in-effect': 'error',
      'react-x/set-state-in-render': 'error',
      'react-x/unsupported-syntax': 'error',
      'react-x/use-memo': 'error',
      'react-x/use-state': 'error',

      'react-rsc/function-definition': 'error',

      'react-dom/no-dangerously-set-innerhtml': 'error',
      'react-dom/no-dangerously-set-innerhtml-with-children': 'error',
      'react-dom/no-find-dom-node': 'error',
      'react-dom/no-flush-sync': 'error',
      'react-dom/no-hydrate': 'error',
      'react-dom/no-missing-button-type': 'error',
      'react-dom/no-missing-iframe-sandbox': 'error',
      'react-dom/no-namespace': 'error',
      'react-dom/no-render': 'error',
      'react-dom/no-render-return-value': 'error',
      'react-dom/no-script-url': 'error',
      'react-dom/no-string-style-prop': 'error',
      'react-dom/no-unknown-property': 'error',
      'react-dom/no-unsafe-iframe-sandbox': 'error',
      'react-dom/no-unsafe-target-blank': 'error',
      'react-dom/no-use-form-state': 'error',
      'react-dom/no-void-elements-with-children': 'error',
      'react-dom/prefer-namespace-import': 'error',

      'react-web-api/no-leaked-event-listener': 'error',
      'react-web-api/no-leaked-interval': 'error',
      'react-web-api/no-leaked-resize-observer': 'error',
      'react-web-api/no-leaked-timeout': 'error',

      'react-naming-convention/context-name': 'error',
      'react-naming-convention/id-name': 'error',
      'react-naming-convention/ref-name': 'error',
    },
  },
]
