// This file is generated by `scripts/sync-oxlint-eslint.ts`.
// Do not edit this file manually.

import type { OxlintOverride } from 'oxlint'

import { GLOB_SRC } from '../globs'

export const command = (): OxlintOverride[] => [
  {
    files: [GLOB_SRC],
    jsPlugins: [{ name: 'command', specifier: 'eslint-plugin-command' }],
    rules: {
      'command/command': 'error',
    },
  },
]
