// This file is generated by `scripts/sync-oxlint-eslint.ts`.
// Do not edit this file manually.

import type { OxlintOverride } from 'oxlint'

import { GLOB_SRC } from '../globs'

export const deMorgan = (): OxlintOverride[] => [
  {
    files: [GLOB_SRC],
    jsPlugins: [{ name: 'de-morgan', specifier: 'eslint-plugin-de-morgan' }],
    rules: {
      'de-morgan/no-negated-conjunction': 'error',
      'de-morgan/no-negated-disjunction': 'error',
    },
  },
]
