// This file is generated by `scripts/sync-oxlint-eslint.ts`.
// Do not edit this file manually.

import type { OxlintOverride } from 'oxlint'

import { GLOB_SRC } from '../globs'

export const nelsonlaidev = (): OxlintOverride => ({
  files: [GLOB_SRC],
  jsPlugins: [{ name: 'nelsonlaidev', specifier: '@nelsonlaidev/eslint-plugin' }],
  rules: {
    'nelsonlaidev/lucide-icon-suffix': 'error',
    'nelsonlaidev/lucide-restrict-import': 'error',
    'nelsonlaidev/shadcn-cn-wrap-variants': 'error',
    'nelsonlaidev/shadcn-cva-variants-suffix': 'error',
    'nelsonlaidev/shadcn-prefer-spinner': 'error',
  },
})
