// This file is generated by `scripts/sync-oxlint-eslint.ts`.
// Do not edit this file manually.

import type { OxlintOverride } from 'oxlint'

import { GLOB_SRC } from '../globs'

export const node = (): OxlintOverride[] => [
  {
    files: [GLOB_SRC],
    plugins: ['node'],
    rules: {
      'node/no-exports-assign': 'error',
      'node/no-path-concat': 'error',
    },
  },
]
