// This file is generated by `scripts/sync-oxlint-eslint.ts`.
// Do not edit this file manually.

import type { OxlintOverride } from 'oxlint'

import { GLOB_SRC } from '../globs'
import { mergeConfig } from '../utils'

export const playwright = (options: Partial<OxlintOverride> = {}): OxlintOverride => {
  const base: OxlintOverride = {
    files: [GLOB_SRC],
    jsPlugins: [{ name: 'playwright', specifier: 'eslint-plugin-playwright' }],
    rules: {
      'eslint/no-empty-pattern': 'off',
      'playwright/consistent-spacing-between-blocks': 'error',
      'playwright/expect-expect': 'error',
      'playwright/max-nested-describe': 'error',
      'playwright/missing-playwright-await': 'error',
      'playwright/no-conditional-expect': 'error',
      'playwright/no-conditional-in-test': 'error',
      'playwright/no-duplicate-hooks': 'error',
      'playwright/no-duplicate-slow': 'error',
      'playwright/no-element-handle': 'error',
      'playwright/no-eval': 'error',
      'playwright/no-focused-test': 'error',
      'playwright/no-force-option': 'error',
      'playwright/no-nested-step': 'error',
      'playwright/no-networkidle': 'error',
      'playwright/no-page-pause': 'error',
      'playwright/no-skipped-test': 'error',
      'playwright/no-standalone-expect': 'error',
      'playwright/no-unsafe-references': 'error',
      'playwright/no-unused-locators': 'error',
      'playwright/no-useless-await': 'error',
      'playwright/no-useless-not': 'error',
      'playwright/no-wait-for-navigation': 'error',
      'playwright/no-wait-for-selector': 'error',
      'playwright/no-wait-for-timeout': 'error',
      'playwright/prefer-hooks-in-order': 'error',
      'playwright/prefer-hooks-on-top': 'error',
      'playwright/prefer-locator': 'error',
      'playwright/prefer-to-have-count': 'error',
      'playwright/prefer-to-have-length': 'error',
      'playwright/prefer-web-first-assertions': 'error',
      'playwright/valid-describe-callback': 'error',
      'playwright/valid-expect': 'error',
      'playwright/valid-expect-in-promise': 'error',
      'playwright/valid-test-tags': 'error',
      'playwright/valid-title': 'error',
    },
  }

  return mergeConfig(base, options)
}
