import type { Overrides } from '../types'

export const react: Overrides = [
  {
    files: ['**/*.{ts,tsx}'],
    plugins: ['react'],
    jsPlugins: [
      'eslint-plugin-react-x',
      'eslint-plugin-react-rsc',
      'eslint-plugin-react-dom',
      'eslint-plugin-react-web-api',
      'eslint-plugin-react-naming-convention',
      { name: 'react-hooks-js', specifier: 'eslint-plugin-react-hooks' },
    ],
    rules: {
      // Disable the following rules because they require type information,
      // which is not implemented in Oxlint JS plugins yet.
      // See: https://oxc.rs/docs/guide/usage/linter/js-plugins.html#api-support

      // 'react-x/no-implicit-children': 'error',
      // 'react-x/no-implicit-key': 'error',
      // 'react-x/no-implicit-ref': 'error',
      // 'react-x/no-leaked-conditional-rendering': 'error',
      // 'react-x/no-unused-props': 'error',

      // Core hooks rules (Rust)
      'react/button-has-type': 'error',
      'react/checked-requires-onchange-or-readonly': 'error',
      'react/display-name': ['error', { checkContextObjects: true }],
      'react/iframe-missing-sandbox': 'error',
      'react/jsx-boolean-value': 'error',
      'react/jsx-curly-brace-presence': ['error', { props: 'never', children: 'never', propElementValues: 'always' }],
      'react/jsx-filename-extension': ['error', { allow: 'as-needed', extensions: ['tsx'] }],
      'react/jsx-fragments': 'error',
      'react/jsx-handler-names': 'error',
      'react/jsx-no-comment-textnodes': 'error',
      'react/jsx-no-constructed-context-values': 'error',
      'react/jsx-no-duplicate-props': 'error',
      'react/jsx-no-script-url': 'error',
      'react/jsx-no-target-blank': 'error',
      'react/jsx-no-undef': 'error',
      'react/jsx-no-useless-fragment': 'error',
      'react/jsx-pascal-case': 'error',
      'react/jsx-props-no-spread-multi': 'error',
      'react/no-children-prop': 'error',
      'react/no-clone-element': 'error',
      'react/no-danger': 'error',
      'react/no-danger-with-children': 'error',
      'react/no-did-mount-set-state': 'error',
      'react/no-direct-mutation-state': 'error',
      'react/no-find-dom-node': 'error',
      'react/no-is-mounted': 'error',
      'react/no-namespace': 'error',
      'react/no-react-children': 'error',
      'react/no-redundant-should-component-update': 'error',
      'react/no-render-return-value': 'error',
      'react/no-set-state': 'error',
      'react/no-string-refs': 'error',
      'react/no-this-in-sfc': 'error',
      'react/no-unknown-property': 'error',
      'react/no-unsafe': 'error',
      'react/no-will-update-set-state': 'error',
      'react/require-render-return': 'error',
      'react/rules-of-hooks': 'error',
      'react/self-closing-comp': 'error',
      'react/state-in-constructor': 'error',

      // Core hooks rules (JavaScript)
      'react-x/jsx-dollar': 'error',
      'react-x/jsx-key-before-spread': 'error',
      'react-x/exhaustive-deps': 'error',
      'react-x/no-access-state-in-setstate': 'error',
      'react-x/no-children-count': 'error',
      'react-x/no-children-for-each': 'error',
      'react-x/no-children-map': 'error',
      'react-x/no-children-only': 'error',
      'react-x/no-children-to-array': 'error',
      'react-x/no-class-component': 'error',
      'react-x/no-component-will-mount': 'error',
      'react-x/no-component-will-receive-props': 'error',
      'react-x/no-component-will-update': 'error',
      'react-x/no-context-provider': 'error',
      'react-x/no-create-ref': 'error',
      'react-x/no-duplicate-key': 'error',
      'react-x/no-forward-ref': 'error',
      'react-x/no-missing-key': 'error',
      'react-x/no-misused-capture-owner-stack': 'error',
      'react-x/no-set-state-in-component-did-update': 'error',
      'react-x/no-unnecessary-use-callback': 'error',
      'react-x/no-unnecessary-use-memo': 'error',
      'react-x/no-unnecessary-use-prefix': 'error',
      'react-x/no-unstable-default-props': 'error',
      'react-x/no-unused-class-component-members': 'error',
      'react-x/no-unused-state': 'error',
      'react-x/no-use-context': 'error',
      'react-x/prefer-destructuring-assignment': 'error',
      'react-x/prefer-namespace-import': 'error',
      'react-x/use-state': 'error',

      // React Server Components rules
      'react-rsc/function-definition': 'error',

      // React DOM rules
      'react-dom/no-flush-sync': 'error',
      'react-dom/no-hydrate': 'error',
      'react-dom/no-render': 'error',
      'react-dom/no-string-style-prop': 'error',
      'react-dom/no-unsafe-iframe-sandbox': 'error',
      'react-dom/no-use-form-state': 'error',
      'react-dom/no-void-elements-with-children': 'error',
      'react-dom/prefer-namespace-import': 'error',

      // Web API rules
      'react-web-api/no-leaked-event-listener': 'error',
      'react-web-api/no-leaked-interval': 'error',
      'react-web-api/no-leaked-resize-observer': 'error',
      'react-web-api/no-leaked-timeout': 'error',

      // Naming Convention rules
      'react-naming-convention/context-name': 'error',
      'react-naming-convention/id-name': 'error',
      'react-naming-convention/ref-name': 'error',

      // React Compiler rules

      // The following rules are not supported in eslint-plugin-react-x yet
      // See: https://www.eslint-react.xyz/docs/migrating-from-eslint-plugin-react-hooks#table
      'react-hooks-js/config': 'error',
      'react-hooks-js/gating': 'error',
      'react-hooks-js/globals': 'error',
      'react-hooks-js/incompatible-library': 'error',
      'react-hooks-js/preserve-manual-memoization': 'error',

      'react-x/error-boundaries': 'error',
      'react-x/component-hook-factories': 'error',
      'react-x/immutability': 'error',
      'react-x/purity': 'error',
      'react-x/refs': 'error',
      'react-x/set-state-in-effect': 'error',
      'react-x/set-state-in-render': 'error',
      'react-x/no-nested-component-definitions': 'error',
      'react-x/no-nested-lazy-component-declarations': 'error',
      'react-x/unsupported-syntax': 'error',
      'react-x/use-memo': 'error',
    },
  },
]
