// This file is generated by `scripts/sync-oxlint-eslint.ts`.
// Do not edit this file manually.

import type { OxlintOverride } from 'oxlint'

import { GLOB_SRC } from '../globs'

export const stylex = (): OxlintOverride => ({
  files: [GLOB_SRC],
  jsPlugins: [{ name: '@stylexjs', specifier: '@stylexjs/eslint-plugin' }],
  rules: {
    '@stylexjs/enforce-extension': 'error',
    '@stylexjs/no-conflicting-props': 'error',
    '@stylexjs/no-legacy-contextual-styles': 'error',
    '@stylexjs/no-lookahead-selectors': 'error',
    '@stylexjs/no-nonstandard-styles': 'error',
    '@stylexjs/no-unused': 'error',
    '@stylexjs/sort-keys': 'error',
    '@stylexjs/valid-shorthands': 'error',
    '@stylexjs/valid-styles': 'error',
  },
})
