// This file is generated by `scripts/sync-oxlint-eslint.ts`.
// Do not edit this file manually.

import type { OxlintOverride } from 'oxlint'

import { GLOB_SRC } from '../globs'
import { mergeConfig } from '../utils'

export const tailwindcss = (options: Partial<OxlintOverride> = {}): OxlintOverride => {
  const base: OxlintOverride = {
    files: [GLOB_SRC],
    jsPlugins: [{ name: 'better-tailwindcss', specifier: 'eslint-plugin-better-tailwindcss' }],
    rules: {
      'better-tailwindcss/enforce-canonical-classes': 'error',
      'better-tailwindcss/enforce-consistent-class-order': 'error',
      'better-tailwindcss/enforce-consistent-variant-order': 'error',
      'better-tailwindcss/no-conflicting-classes': 'error',
      'better-tailwindcss/no-deprecated-classes': 'error',
      'better-tailwindcss/no-duplicate-classes': 'error',
      'better-tailwindcss/no-restricted-classes': 'error',
      'better-tailwindcss/no-unknown-classes': 'error',
      'better-tailwindcss/no-unnecessary-whitespace': 'error',
    },
  }

  return mergeConfig(base, options)
}
