// This file is generated by `scripts/sync-oxlint-eslint.ts`.
// Do not edit this file manually.

import type { OxlintOverride } from 'oxlint'

import { GLOB_SRC } from '../globs'

export const typescript = (): OxlintOverride[] => [
  {
    files: [GLOB_SRC],
    plugins: ['typescript'],
    rules: {
      'typescript/adjacent-overload-signatures': 'error',
      'typescript/array-type': [
        'error',
        {
          default: 'array-simple',
          readonly: 'array-simple',
        },
      ],
      'typescript/await-thenable': 'error',
      'typescript/ban-ts-comment': [
        'error',
        {
          minimumDescriptionLength: 10,
        },
      ],
      'typescript/ban-tslint-comment': 'error',
      'typescript/class-literal-property-style': 'error',
      'typescript/consistent-generic-constructors': 'error',
      'typescript/consistent-indexed-object-style': 'error',
      'typescript/consistent-type-assertions': 'error',
      'typescript/consistent-type-definitions': ['error', 'type'],
      'typescript/consistent-type-exports': [
        'error',
        {
          fixMixedExportsWithInlineTypeSpecifier: false,
        },
      ],
      'typescript/consistent-type-imports': [
        'error',
        {
          prefer: 'type-imports',
          fixStyle: 'separate-type-imports',
        },
      ],
      'typescript/dot-notation': 'error',
      'typescript/no-array-delete': 'error',
      'typescript/no-base-to-string': 'error',
      'typescript/no-confusing-non-null-assertion': 'error',
      'typescript/no-confusing-void-expression': 'error',
      'typescript/no-deprecated': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-duplicate-type-constituents': 'error',
      'typescript/no-dynamic-delete': 'error',
      'typescript/no-empty-object-type': [
        'error',
        {
          allowInterfaces: 'with-single-extends',
        },
      ],
      'typescript/no-explicit-any': 'error',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-extraneous-class': 'error',
      'typescript/no-floating-promises': 'error',
      'typescript/no-for-in-array': 'error',
      'typescript/no-implied-eval': 'error',
      'typescript/no-import-type-side-effects': 'error',
      'typescript/no-inferrable-types': 'error',
      'typescript/no-invalid-void-type': 'error',
      'typescript/no-meaningless-void-operator': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-misused-promises': [
        'error',
        {
          checksVoidReturn: false,
        },
      ],
      'typescript/no-misused-spread': 'error',
      'typescript/no-mixed-enums': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-nullish-coalescing': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-non-null-assertion': 'error',
      'typescript/no-redundant-type-constituents': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-restricted-types': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-boolean-literal-compare': 'error',
      'typescript/no-unnecessary-condition': 'error',
      'typescript/no-unnecessary-parameter-property-assignment': 'error',
      'typescript/no-unnecessary-template-expression': 'error',
      'typescript/no-unnecessary-type-arguments': 'error',
      'typescript/no-unnecessary-type-assertion': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unnecessary-type-conversion': 'error',
      'typescript/no-unnecessary-type-parameters': 'error',
      'typescript/no-unsafe-argument': 'error',
      'typescript/no-unsafe-assignment': 'error',
      'typescript/no-unsafe-call': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unsafe-enum-comparison': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-unsafe-member-access': 'error',
      'typescript/no-unsafe-return': 'error',
      'typescript/no-unsafe-unary-minus': 'error',
      'typescript/no-useless-default-assignment': 'error',
      'typescript/no-useless-empty-export': 'error',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/non-nullable-type-assertion-style': 'error',
      'typescript/only-throw-error': [
        'error',
        {
          allow: [
            {
              from: 'package',
              package: '@tanstack/router-core',
              name: 'Redirect',
            },
          ],
        },
      ],
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-enum-initializers': 'error',
      'typescript/prefer-find': 'error',
      'typescript/prefer-for-of': 'error',
      'typescript/prefer-function-type': 'error',
      'typescript/prefer-includes': 'error',
      'typescript/prefer-literal-enum-member': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/prefer-nullish-coalescing': 'error',
      'typescript/prefer-optional-chain': 'error',
      'typescript/prefer-promise-reject-errors': 'error',
      'typescript/prefer-reduce-type-parameter': 'error',
      'typescript/prefer-regexp-exec': 'error',
      'typescript/prefer-return-this-type': 'error',
      'typescript/prefer-string-starts-ends-with': 'error',
      'typescript/promise-function-async': 'error',
      'typescript/related-getter-setter-pairs': 'error',
      'typescript/require-array-sort-compare': 'error',
      'typescript/require-await': 'error',
      'typescript/restrict-plus-operands': [
        'error',
        {
          allowAny: false,
          allowBoolean: false,
          allowNullish: false,
          allowNumberAndString: false,
          allowRegExp: false,
        },
      ],
      'typescript/restrict-template-expressions': [
        'error',
        {
          allowNumber: true,
        },
      ],
      'typescript/return-await': ['error', 'error-handling-correctness-only'],
      'typescript/switch-exhaustiveness-check': 'error',
      'typescript/triple-slash-reference': 'error',
      'typescript/unbound-method': 'error',
      'typescript/unified-signatures': 'error',
      'typescript/use-unknown-in-catch-callback-variable': 'error',
    },
  },
  {
    files: ['**/*.d.ts'],
    plugins: ['typescript'],
    rules: {
      // Similar to the above rule, interfaces support index signatures only when
      // we define object types with them.
      'typescript/consistent-indexed-object-style': 'off',
      // We sometimes need to use `interface` in declaration files,
      // especially when we want to extend from a type from another package,
      // and that type is an interface.
      'typescript/consistent-type-definitions': 'off',
    },
  },
]
