// This file is generated by `scripts/sync-oxlint-eslint.ts`.
// Do not edit this file manually.

import type { OxlintOverride } from 'oxlint'

import { GLOB_SRC } from '../globs'
import { mergeConfig } from '../utils'

export const vitest = (options: Partial<OxlintOverride> = {}): OxlintOverride => {
  const base: OxlintOverride = {
    files: [GLOB_SRC],
    plugins: ['vitest'],
    rules: {
      'vitest/consistent-test-it': [
        'error',
        {
          fn: 'test',
        },
      ],
      'vitest/expect-expect': 'error',
      'vitest/no-commented-out-tests': 'error',
      'vitest/no-conditional-expect': 'error',
      'vitest/no-disabled-tests': 'error',
      'vitest/no-focused-tests': 'error',
      'vitest/no-identical-title': 'error',
      'vitest/no-import-node-test': 'error',
      'vitest/no-interpolation-in-snapshots': 'error',
      'vitest/no-mocks-import': 'error',
      'vitest/no-standalone-expect': 'error',
      'vitest/no-unneeded-async-expect-function': 'error',
      'vitest/prefer-called-exactly-once-with': 'error',
      'vitest/prefer-mock-return-shorthand': 'error',
      'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
      'vitest/valid-describe-callback': 'error',
      'vitest/valid-expect': 'error',
      'vitest/valid-expect-in-promise': 'error',
      'vitest/valid-title': 'error',
      'vitest/warn-todo': 'error',
    },
  }

  return mergeConfig(base, options)
}
