// This file is generated by `scripts/sync-oxlint-eslint.ts`.
// Do not edit this file manually.

import type { OxlintOverride } from 'oxlint'
import type { VitestConfig } from '../types/vitest'

export const vitest = (config: VitestConfig): OxlintOverride[] => [
  {
    files: config.files,
    plugins: ['vitest', 'jest'],
    rules: {
      'jest/no-standalone-expect': 'error',
      'jest/no-unneeded-async-expect-function': 'error',
      'jest/prefer-mock-return-shorthand': 'error',
      'jest/valid-describe-callback': 'error',
      'jest/valid-expect-in-promise': 'error',
      'vitest/consistent-test-it': [
        'error',
        {
          fn: 'test',
        },
      ],
      'vitest/expect-expect': 'error',
      'vitest/no-commented-out-tests': 'error',
      'vitest/no-conditional-expect': 'error',
      'vitest/no-disabled-tests': 'error',
      'vitest/no-focused-tests': 'error',
      'vitest/no-identical-title': 'error',
      'vitest/no-import-node-test': 'error',
      'vitest/no-interpolation-in-snapshots': 'error',
      'vitest/no-mocks-import': 'error',
      'vitest/prefer-called-exactly-once-with': 'error',
      'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
      'vitest/valid-expect': 'error',
      'vitest/valid-title': 'error',
      'vitest/warn-todo': 'error',
    },
  },
]
