// This file is generated by `scripts/sync-oxlint-eslint.ts`.
// Do not edit this file manually.

import type { OxlintOverride } from 'oxlint'

import { GLOB_SRC } from '../globs'

export const zod = (): OxlintOverride => ({
  files: [GLOB_SRC],
  jsPlugins: [{ name: 'import-zod', specifier: 'eslint-plugin-import-zod' }],
  rules: {
    'import-zod/prefer-zod-namespace': 'error',
  },
})
