// Inspired by @oxlint/migrate
// https://github.com/oxc-project/oxlint-migrate/blob/5e7463f9cc49d1074efe2230264b0068cb89ecfc/scripts/traverse-rules.ts

import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { format, resolveConfig } from 'prettier'

type OxlintRule = {
  value: string
  scope: string
  category: string
  type_aware: boolean
  fix?: string
  default?: boolean
  docs_url?: string
}

type EslintFlatConfig = {
  name?: string
  rules?: Record<string, unknown>
}

type EnabledRuleValue = 'error' | ['error', ...unknown[]]
type SyncedRuleValue = 'off' | EnabledRuleValue

type RuleLookup = Map<string, Set<string>>

type RuleGroupManifest = {
  sourceConfigNames: string[]
  filesExpression: string
  pluginsExpression: string
  commentByRuleName?: Record<string, string[]>
  preserveOffRules?: boolean
}

type PresetManifestEntry = {
  id: string
  sourceModulePath: string
  sourceExportName: string
  sourceArgs?: unknown[]
  targetFilePath: string
  targetExportName: string
  functionSignature: string
  imports: string[]
  oxlintScope: string
  oxlintFallbackScopes?: string[]
  remapRuleName: (ruleName: string) => string | null
  groups: RuleGroupManifest[]
}

type RuleComparisonGroupManifest = {
  sourceConfigNames: string[]
  preserveOffRules?: boolean
}

type JsPluginComparisonManifestEntry = {
  id: string
  sourceModulePath: string
  sourceExportName: string
  sourceArgs?: unknown[]
  targetModulePath?: string
  targetExportName?: string
  targetArgs?: unknown[]
  remapRuleName: (ruleName: string) => string | null
  groups: RuleComparisonGroupManifest[]
}

type UnsupportedRule = {
  presetId: string
  sourceConfigNames: string[]
  eslintRuleName: string
  oxlintRuleName: string
}

type SyncResult = {
  staleFilePaths: string[]
  unsupportedRules: UnsupportedRule[]
  updatedFilePaths: string[]
}

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const GENERATED_HEADER = [
  '// This file is generated by `scripts/sync-oxlint-eslint.ts`.',
  '// Do not edit this file manually.',
].join('\n')

function identityRemapper(ruleName: string) {
  return ruleName
}

function createPrefixRemapper(from: string, to: string) {
  return (ruleName: string) => (ruleName.startsWith(from) ? `${to}${ruleName.slice(from.length)}` : null)
}

function createCompositeRemapper(...remappers: Array<(ruleName: string) => string | null>) {
  return (ruleName: string) => {
    for (const remapper of remappers) {
      const remappedRuleName = remapper(ruleName)

      if (remappedRuleName) {
        return remappedRuleName
      }
    }

    return null
  }
}

export const PRESET_MANIFEST: PresetManifestEntry[] = [
  {
    id: 'eslint',
    sourceModulePath: 'packages/eslint-config/src/configs/javascript.ts',
    sourceExportName: 'javascript',
    targetFilePath: 'packages/oxlint-config/src/configs/eslint.ts',
    targetExportName: 'eslint',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'eslint',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/javascript/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['eslint']",
      },
    ],
  },
  {
    id: 'unicorn',
    sourceModulePath: 'packages/eslint-config/src/configs/unicorn.ts',
    sourceExportName: 'unicorn',
    targetFilePath: 'packages/oxlint-config/src/configs/unicorn.ts',
    targetExportName: 'unicorn',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'unicorn',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/unicorn/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['unicorn']",
      },
    ],
  },
  {
    id: 'typescript',
    sourceModulePath: 'packages/eslint-config/src/configs/typescript.ts',
    sourceExportName: 'typescript',
    targetFilePath: 'packages/oxlint-config/src/configs/typescript.ts',
    targetExportName: 'typescript',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'typescript',
    remapRuleName: createPrefixRemapper('@typescript-eslint/', 'typescript/'),
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/typescript/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['typescript']",
      },
      {
        sourceConfigNames: ['nelsonlaidev/typescript/declarations'],
        filesExpression: "['**/*.d.ts']",
        pluginsExpression: "['typescript']",
        commentByRuleName: {
          'typescript/consistent-type-definitions': [
            '// We sometimes need to use `interface` in declaration files,',
            '// especially when we want to extend from a type from another package,',
            '// and that type is an interface.',
          ],
          'typescript/consistent-indexed-object-style': [
            '// Similar to the above rule, interfaces support index signatures only when',
            '// we define object types with them.',
          ],
        },
        preserveOffRules: true,
      },
    ],
  },
  {
    id: 'import',
    sourceModulePath: 'packages/eslint-config/src/configs/import-x.ts',
    sourceExportName: 'importX',
    targetFilePath: 'packages/oxlint-config/src/configs/imports.ts',
    targetExportName: 'imports',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'import',
    remapRuleName: createPrefixRemapper('import-x/', 'import/'),
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/import-x/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['import']",
      },
    ],
  },
  {
    id: 'jsdoc',
    sourceModulePath: 'packages/eslint-config/src/configs/jsdoc.ts',
    sourceExportName: 'jsdoc',
    targetFilePath: 'packages/oxlint-config/src/configs/jsdoc.ts',
    targetExportName: 'jsdoc',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'jsdoc',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/jsdoc/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['jsdoc']",
      },
    ],
  },
  {
    id: 'vitest',
    sourceModulePath: 'packages/eslint-config/src/configs/vitest.ts',
    sourceExportName: 'vitest',
    sourceArgs: [{ files: ['__SYNC_PLACEHOLDER__'] }],
    targetFilePath: 'packages/oxlint-config/src/configs/vitest.ts',
    targetExportName: 'vitest',
    functionSignature: '(config: VitestConfig): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", "import type { VitestConfig } from '../types/vitest'"],
    oxlintScope: 'vitest',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/vitest/rules'],
        filesExpression: 'config.files',
        pluginsExpression: "['vitest']",
      },
    ],
  },
  {
    id: 'jsx-a11y',
    sourceModulePath: 'packages/eslint-config/src/configs/jsx-a11y.ts',
    sourceExportName: 'jsxA11y',
    targetFilePath: 'packages/oxlint-config/src/configs/jsx-a11y.ts',
    targetExportName: 'jsxA11y',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'jsx_a11y',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/jsx-a11y/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['jsx-a11y']",
      },
    ],
  },
  {
    id: 'nextjs',
    sourceModulePath: 'packages/eslint-config/src/configs/nextjs.ts',
    sourceExportName: 'nextjs',
    targetFilePath: 'packages/oxlint-config/src/configs/nextjs.ts',
    targetExportName: 'nextjs',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'nextjs',
    remapRuleName: createPrefixRemapper('@next/next/', 'nextjs/'),
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/nextjs/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['nextjs']",
      },
    ],
  },
  {
    id: 'promise',
    sourceModulePath: 'packages/eslint-config/src/configs/promise.ts',
    sourceExportName: 'promise',
    targetFilePath: 'packages/oxlint-config/src/configs/promise.ts',
    targetExportName: 'promise',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'promise',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/promise/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['promise']",
      },
    ],
  },
  {
    id: 'node',
    sourceModulePath: 'packages/eslint-config/src/configs/node.ts',
    sourceExportName: 'node',
    targetFilePath: 'packages/oxlint-config/src/configs/node.ts',
    targetExportName: 'node',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'node',
    remapRuleName: createPrefixRemapper('n/', 'node/'),
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/node/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['node']",
      },
    ],
  },
]

export const JS_PLUGIN_COMPARISON_MANIFEST: JsPluginComparisonManifestEntry[] = [
  {
    id: 'de-morgan',
    sourceModulePath: 'packages/eslint-config/src/configs/de-morgan.ts',
    sourceExportName: 'deMorgan',
    targetModulePath: 'packages/oxlint-config/src/configs/de-morgan.ts',
    targetExportName: 'deMorgan',
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/de-morgan/rules'] }],
  },
  {
    id: 'import-sort',
    sourceModulePath: 'packages/eslint-config/src/configs/import-sort.ts',
    sourceExportName: 'importSort',
    targetModulePath: 'packages/oxlint-config/src/configs/import-sort.ts',
    targetExportName: 'importSort',
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/import-sort/rules'] }],
  },
  {
    id: 'nelsonlaidev',
    sourceModulePath: 'packages/eslint-config/src/configs/nelsonlaidev.ts',
    sourceExportName: 'nelsonlaidev',
    targetModulePath: 'packages/oxlint-config/src/configs/nelsonlaidev.ts',
    targetExportName: 'nelsonlaidev',
    remapRuleName: createPrefixRemapper('@nelsonlaidev/', 'nelsonlaidev/'),
    groups: [{ sourceConfigNames: ['nelsonlaidev/nelsonlaidev/rules'] }],
  },
  {
    id: 'playwright',
    sourceModulePath: 'packages/eslint-config/src/configs/playwright.ts',
    sourceExportName: 'playwright',
    sourceArgs: [{ files: ['__SYNC_PLACEHOLDER__'] }],
    targetModulePath: 'packages/oxlint-config/src/configs/playwright.ts',
    targetExportName: 'playwright',
    targetArgs: [{ files: ['__SYNC_PLACEHOLDER__'] }],
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/playwright/rules'] }],
  },
  {
    id: 'react',
    sourceModulePath: 'packages/eslint-config/src/configs/react.ts',
    sourceExportName: 'react',
    targetModulePath: 'packages/oxlint-config/src/configs/react.ts',
    targetExportName: 'react',
    remapRuleName: createCompositeRemapper(createPrefixRemapper('react-hooks/', 'react-hooks-js/'), identityRemapper),
    groups: [{ sourceConfigNames: ['nelsonlaidev/react/rules'] }],
  },
  {
    id: 'regexp',
    sourceModulePath: 'packages/eslint-config/src/configs/regexp.ts',
    sourceExportName: 'regexp',
    targetModulePath: 'packages/oxlint-config/src/configs/regexp.ts',
    targetExportName: 'regexp',
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/regexp/rules'] }],
  },
  {
    id: 'sonarjs',
    sourceModulePath: 'packages/eslint-config/src/configs/sonarjs.ts',
    sourceExportName: 'sonarjs',
    targetModulePath: 'packages/oxlint-config/src/configs/sonarjs.ts',
    targetExportName: 'sonarjs',
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/sonarjs/rules'] }],
  },
  {
    id: 'stylistic',
    sourceModulePath: 'packages/eslint-config/src/configs/stylistic.ts',
    sourceExportName: 'stylistic',
    targetModulePath: 'packages/oxlint-config/src/configs/stylistic.ts',
    targetExportName: 'stylistic',
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/stylistic/rules'] }],
  },
  {
    id: 'tailwindcss',
    sourceModulePath: 'packages/eslint-config/src/configs/tailwindcss.ts',
    sourceExportName: 'tailwindcss',
    sourceArgs: [{}],
    targetModulePath: 'packages/oxlint-config/src/configs/tailwindcss.ts',
    targetExportName: 'tailwindcss',
    targetArgs: [{}],
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/tailwindcss/rules'] }],
  },
  {
    id: 'unused-imports',
    sourceModulePath: 'packages/eslint-config/src/configs/unused-imports.ts',
    sourceExportName: 'unusedImports',
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/unused-imports/rules'] }],
  },
  {
    id: 'zod',
    sourceModulePath: 'packages/eslint-config/src/configs/zod.ts',
    sourceExportName: 'zod',
    targetModulePath: 'packages/oxlint-config/src/configs/zod.ts',
    targetExportName: 'zod',
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/zod/rules'] }],
  },
]

export function readRulesFromCommand(): OxlintRule[] {
  const oxlintOutput = execSync(`pnpm -C packages/oxlint-config exec oxlint --rules --format=json`, {
    cwd: ROOT_DIR,
    encoding: 'utf-8',
    stdio: 'pipe',
  })

  return JSON.parse(oxlintOutput) as OxlintRule[]
}

export function buildSupportedRuleLookup(rules: OxlintRule[]): RuleLookup {
  const lookup = new Map<string, Set<string>>()

  for (const rule of rules) {
    const supportedRules = lookup.get(rule.scope) ?? new Set<string>()
    supportedRules.add(rule.value)
    lookup.set(rule.scope, supportedRules)
  }

  return lookup
}

export function normalizeRuleValue(rawValue: unknown): SyncedRuleValue {
  if (Array.isArray(rawValue)) {
    const [level, ...options] = rawValue as readonly unknown[]
    const normalizedLevel = normalizeSeverity(level)

    if (normalizedLevel === 'off') {
      return 'off'
    }

    return options.length === 0 ? 'error' : ['error', ...options]
  }

  return normalizeSeverity(rawValue)
}

function normalizeSeverity(level: unknown): 'error' | 'off' {
  if (level === 'off' || level === 0) {
    return 'off'
  }

  if (level === 'warn' || level === 1 || level === 'error' || level === 2) {
    return 'error'
  }

  throw new Error(`Unsupported ESLint rule severity: ${JSON.stringify(level)}`)
}

function resolveFromRoot(filePath: string) {
  return path.join(ROOT_DIR, filePath)
}

async function loadConfigFactoryOutputs({
  args = [],
  exportName,
  modulePath,
}: {
  args?: unknown[]
  exportName: string
  modulePath: string
}): Promise<EslintFlatConfig[]> {
  const moduleUrl = pathToFileURL(resolveFromRoot(modulePath)).href
  const sourceModule = (await import(moduleUrl)) as Record<string, (...args: unknown[]) => EslintFlatConfig[]>
  const sourceFactory = sourceModule[exportName]

  if (typeof sourceFactory !== 'function') {
    throw new TypeError(`Missing export "${exportName}" in ${modulePath}`)
  }

  return sourceFactory(...args)
}

async function loadSourceConfigs(entry: PresetManifestEntry): Promise<EslintFlatConfig[]> {
  return loadConfigFactoryOutputs({
    args: entry.sourceArgs,
    exportName: entry.sourceExportName,
    modulePath: entry.sourceModulePath,
  })
}

function getConfigByName(configs: EslintFlatConfig[], configName: string): EslintFlatConfig {
  const config = configs.find((item) => item.name === configName)

  if (!config) {
    throw new Error(`Unable to find ESLint config "${configName}"`)
  }

  return config
}

export function collectRulesForGroup(configs: EslintFlatConfig[], group: RuleGroupManifest): Record<string, unknown> {
  const collectedRules: Record<string, unknown> = {}

  for (const configName of group.sourceConfigNames) {
    const config = getConfigByName(configs, configName)
    Object.assign(collectedRules, config.rules)
  }

  return collectedRules
}

function collectRulesForConfigNames(configs: EslintFlatConfig[], configNames: string[]): Record<string, unknown> {
  const collectedRules: Record<string, unknown> = {}

  for (const configName of configNames) {
    const config = getConfigByName(configs, configName)
    Object.assign(collectedRules, config.rules)
  }

  return collectedRules
}

function collectRules(configs: EslintFlatConfig[]): Record<string, unknown> {
  const collectedRules: Record<string, unknown> = {}

  for (const config of configs) {
    Object.assign(collectedRules, config.rules)
  }

  return collectedRules
}

function getScopedRuleValue(ruleName: string) {
  const slashIndex = ruleName.indexOf('/')
  return slashIndex === -1 ? ruleName : ruleName.slice(slashIndex + 1)
}

export function mapToSupportedOxlintRules(
  rules: Record<string, unknown>,
  entry: Pick<PresetManifestEntry, 'oxlintScope' | 'oxlintFallbackScopes' | 'remapRuleName'>,
  supportedRules: RuleLookup,
  {
    onUnsupportedRule,
    preserveOffRules = false,
  }: {
    onUnsupportedRule?: (rule: { eslintRuleName: string; oxlintRuleName: string }) => void
    preserveOffRules?: boolean
  } = {},
): Record<string, SyncedRuleValue> {
  const syncedRules = new Map<string, SyncedRuleValue>()

  for (const [eslintRuleName, rawValue] of Object.entries(rules)) {
    const normalizedValue = normalizeRuleValue(rawValue)

    if (normalizedValue === 'off' && !preserveOffRules) {
      continue
    }

    const remappedRuleName = entry.remapRuleName(eslintRuleName)

    if (!remappedRuleName) {
      continue
    }

    const oxlintRuleName = resolveSupportedOxlintRuleName(remappedRuleName, entry, supportedRules)

    if (!oxlintRuleName) {
      onUnsupportedRule?.({ eslintRuleName, oxlintRuleName: remappedRuleName })
      continue
    }

    syncedRules.set(oxlintRuleName, normalizedValue)
  }

  return Object.fromEntries(
    syncedRules
      .entries()
      .toArray()
      .toSorted(([left], [right]) => left.localeCompare(right)),
  )
}

function resolveSupportedOxlintRuleName(
  ruleName: string,
  entry: Pick<PresetManifestEntry, 'oxlintScope' | 'oxlintFallbackScopes'>,
  supportedRules: RuleLookup,
) {
  const ruleValue = getScopedRuleValue(ruleName)

  if (supportedRules.get(entry.oxlintScope)?.has(ruleValue)) {
    return ruleName
  }

  for (const fallbackScope of entry.oxlintFallbackScopes ?? []) {
    if (supportedRules.get(fallbackScope)?.has(ruleValue)) {
      return `${fallbackScope}/${ruleValue}`
    }
  }

  return null
}

function renderRuleEntries(rules: Record<string, SyncedRuleValue>, comments: Record<string, string[]> = {}) {
  const lines: string[] = []

  for (const [ruleName, value] of Object.entries(rules)) {
    for (const commentLine of comments[ruleName] ?? []) {
      lines.push(`      ${commentLine}`)
    }

    const renderedEntry = JSON.stringify({ [ruleName]: value }, null, 2)
      .split('\n')
      .slice(1, -1)
      .map((line) => `    ${line}`)

    const lastIndex = renderedEntry.length - 1

    if (lastIndex < 0) {
      continue
    }

    renderedEntry[lastIndex] = `${renderedEntry[lastIndex]},`
    lines.push(...renderedEntry)
  }

  return lines
}

function renderRulesObject(rules: Record<string, SyncedRuleValue>, comments?: Record<string, string[]>) {
  const renderedEntries = renderRuleEntries(rules, comments)

  if (renderedEntries.length === 0) {
    return '    rules: {},'
  }

  return ['    rules: {', ...renderedEntries, '    },'].join('\n')
}

function renderOverride(group: RuleGroupManifest, rules: Record<string, SyncedRuleValue>) {
  return [
    '  {',
    `    files: ${group.filesExpression},`,
    `    plugins: ${group.pluginsExpression},`,
    renderRulesObject(rules, group.commentByRuleName),
    '  }',
  ].join('\n')
}

async function formatGeneratedSource(source: string, targetFilePath: string) {
  const absoluteTargetPath = resolveFromRoot(targetFilePath)
  const prettierConfig = (await resolveConfig(absoluteTargetPath)) ?? {}
  return format(source, {
    ...prettierConfig,
    filepath: absoluteTargetPath,
    parser: 'typescript',
  })
}

export async function generatePresetContent(entry: PresetManifestEntry, supportedRules: RuleLookup): Promise<string> {
  const sourceConfigs = await loadSourceConfigs(entry)
  const renderedOverrides = entry.groups.map((group) => {
    const eslintRules = collectRulesForGroup(sourceConfigs, group)
    const syncedRules = mapToSupportedOxlintRules(eslintRules, entry, supportedRules, {
      preserveOffRules: group.preserveOffRules,
    })
    return renderOverride(group, syncedRules)
  })

  const source = [
    GENERATED_HEADER,
    '',
    ...entry.imports,
    '',
    `export const ${entry.targetExportName} = ${entry.functionSignature} => [`,
    renderedOverrides.join(',\n'),
    ']',
    '',
  ].join('\n')

  return formatGeneratedSource(source, entry.targetFilePath)
}

export async function collectUnsupportedRules(supportedRules: RuleLookup): Promise<UnsupportedRule[]> {
  const [presetUnsupportedRules, jsPluginUnsupportedRules] = await Promise.all([
    collectUnsupportedPresetRules(supportedRules),
    collectUnsupportedJsPluginRules(),
  ])

  return [...presetUnsupportedRules, ...jsPluginUnsupportedRules].toSorted((left, right) => {
    const presetOrder = left.presetId.localeCompare(right.presetId)

    if (presetOrder !== 0) {
      return presetOrder
    }

    return left.oxlintRuleName.localeCompare(right.oxlintRuleName)
  })
}

async function collectUnsupportedPresetRules(supportedRules: RuleLookup): Promise<UnsupportedRule[]> {
  const unsupportedRules: UnsupportedRule[] = []

  await Promise.all(
    PRESET_MANIFEST.map(async (entry) => {
      const sourceConfigs = await loadSourceConfigs(entry)

      for (const group of entry.groups) {
        const eslintRules = collectRulesForGroup(sourceConfigs, group)

        mapToSupportedOxlintRules(eslintRules, entry, supportedRules, {
          onUnsupportedRule: ({ eslintRuleName, oxlintRuleName }) => {
            unsupportedRules.push({
              presetId: entry.id,
              sourceConfigNames: group.sourceConfigNames,
              eslintRuleName,
              oxlintRuleName,
            })
          },
          preserveOffRules: group.preserveOffRules,
        })
      }
    }),
  )

  return unsupportedRules
}

async function collectUnsupportedJsPluginRules(): Promise<UnsupportedRule[]> {
  const unsupportedRules: UnsupportedRule[] = []

  await Promise.all(
    JS_PLUGIN_COMPARISON_MANIFEST.map(async (entry) => {
      const [sourceConfigs, targetConfigs] = await Promise.all([
        loadConfigFactoryOutputs({
          args: entry.sourceArgs,
          exportName: entry.sourceExportName,
          modulePath: entry.sourceModulePath,
        }),
        entry.targetModulePath && entry.targetExportName
          ? loadConfigFactoryOutputs({
              args: entry.targetArgs,
              exportName: entry.targetExportName,
              modulePath: entry.targetModulePath,
            })
          : Promise.resolve([]),
      ])
      const targetRules = collectRules(targetConfigs)

      for (const group of entry.groups) {
        const sourceRules = collectRulesForConfigNames(sourceConfigs, group.sourceConfigNames)
        collectUnsupportedRulesForComparison(sourceRules, entry, targetRules, group, unsupportedRules)
      }
    }),
  )

  return unsupportedRules
}

function collectUnsupportedRulesForComparison(
  rules: Record<string, unknown>,
  entry: Pick<JsPluginComparisonManifestEntry, 'id' | 'remapRuleName'>,
  targetRules: Record<string, unknown>,
  group: RuleComparisonGroupManifest,
  unsupportedRules: UnsupportedRule[],
) {
  for (const [eslintRuleName, rawValue] of Object.entries(rules)) {
    const normalizedValue = normalizeRuleValue(rawValue)

    if (normalizedValue === 'off' && !group.preserveOffRules) {
      continue
    }

    const oxlintRuleName = entry.remapRuleName(eslintRuleName)

    if (!oxlintRuleName || Object.hasOwn(targetRules, oxlintRuleName)) {
      continue
    }

    unsupportedRules.push({
      presetId: entry.id,
      sourceConfigNames: group.sourceConfigNames,
      eslintRuleName,
      oxlintRuleName,
    })
  }
}

export async function generatePresetOutputs(supportedRules: RuleLookup) {
  return Promise.all(
    PRESET_MANIFEST.map(async (entry) => ({
      entry,
      content: await generatePresetContent(entry, supportedRules),
    })),
  )
}

export async function syncOxlintEslint({ check = false }: { check?: boolean } = {}): Promise<SyncResult> {
  const supportedRules = buildSupportedRuleLookup(readRulesFromCommand())
  const [presetOutputs, unsupportedRules] = await Promise.all([
    generatePresetOutputs(supportedRules),
    collectUnsupportedRules(supportedRules),
  ])

  const staleFilePaths: string[] = []
  const updatedFilePaths: string[] = []

  for (const { entry, content } of presetOutputs) {
    const absoluteTargetPath = resolveFromRoot(entry.targetFilePath)
    const currentContent = readFileSync(absoluteTargetPath, 'utf-8')

    if (currentContent === content) {
      continue
    }

    staleFilePaths.push(absoluteTargetPath)

    if (!check) {
      writeFileSync(absoluteTargetPath, content)
      updatedFilePaths.push(absoluteTargetPath)
    }
  }

  return { staleFilePaths, unsupportedRules, updatedFilePaths }
}

function logUnsupportedRuleSummary(unsupportedRules: UnsupportedRule[]) {
  if (unsupportedRules.length === 0) {
    console.log('All configured ESLint rules are currently supported by Oxlint.')
    return
  }

  console.log(`Oxlint does not currently support ${unsupportedRules.length} configured ESLint rule(s).`)

  const unsupportedCountByPresetId = Map.groupBy(unsupportedRules, (rule) => rule.presetId)

  for (const [presetId, rules] of unsupportedCountByPresetId
    .entries()
    .toArray()
    .toSorted(([left], [right]) => left.localeCompare(right))) {
    console.log(`- ${presetId}: ${rules.length}`)

    for (const rule of rules) {
      const ruleName =
        rule.eslintRuleName === rule.oxlintRuleName
          ? rule.eslintRuleName
          : `${rule.eslintRuleName} -> ${rule.oxlintRuleName}`

      console.log(`  - ${ruleName}`)
    }
  }
}

async function main() {
  const check = process.argv.includes('--check')
  const result = await syncOxlintEslint({ check })

  logUnsupportedRuleSummary(result.unsupportedRules)

  if (check && result.staleFilePaths.length > 0) {
    console.error('Oxlint preset files are out of sync:')

    for (const filePath of result.staleFilePaths) {
      console.error(`- ${path.relative(ROOT_DIR, filePath)}`)
    }

    process.exitCode = 1
    return
  }

  if (check) {
    console.log('Oxlint preset files are in sync.')
    return
  }

  if (result.updatedFilePaths.length === 0) {
    console.log('Oxlint preset files are already up to date.')
    return
  }

  console.log(`Updated ${result.updatedFilePaths.length} Oxlint preset file(s):`)

  for (const filePath of result.updatedFilePaths) {
    console.log(`- ${path.relative(ROOT_DIR, filePath)}`)
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main()
}
