// Inspired by @oxlint/migrate
// https://github.com/oxc-project/oxlint-migrate/blob/5e7463f9cc49d1074efe2230264b0068cb89ecfc/scripts/traverse-rules.ts

import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { format, resolveConfig } from 'prettier'

type OxlintRule = {
  value: string
  scope: string
  category: string
  type_aware: boolean
  fix?: string
  default?: boolean
  docs_url?: string
}

type EslintFlatConfig = {
  name?: string
  rules?: Record<string, unknown>
}

type EnabledRuleValue = 'error' | ['error', ...unknown[]]
type SyncedRuleValue = 'off' | EnabledRuleValue

type RuleLookup = Map<string, Set<string>>

type RuleGroupManifest = {
  sourceConfigNames: string[]
  filesExpression: string
  pluginsExpression: string
  commentByRuleName?: Record<string, string[]>
  preserveOffRules?: boolean
}

type PresetManifestEntry = {
  id: string
  sourceModulePath: string
  sourceExportName: string
  sourceArgs?: unknown[]
  targetFilePath: string
  targetExportName: string
  functionSignature: string
  imports: string[]
  oxlintScope: string
  oxlintFallbackScopes?: string[]
  remapRuleName: (ruleName: string) => string | null
  groups: RuleGroupManifest[]
}

type SyncResult = {
  staleFilePaths: string[]
  updatedFilePaths: string[]
}

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const GENERATED_HEADER = [
  '// This file is generated by `scripts/sync-oxlint-eslint.ts`.',
  '// Do not edit this file manually.',
].join('\n')

function identityRemapper(ruleName: string) {
  return ruleName
}

function createPrefixRemapper(from: string, to: string) {
  return (ruleName: string) => (ruleName.startsWith(from) ? `${to}${ruleName.slice(from.length)}` : null)
}

export const PRESET_MANIFEST: PresetManifestEntry[] = [
  {
    id: 'eslint',
    sourceModulePath: 'packages/eslint-config/src/configs/javascript.ts',
    sourceExportName: 'javascript',
    targetFilePath: 'packages/oxlint-config/src/configs/eslint.ts',
    targetExportName: 'eslint',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'eslint',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/javascript/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['eslint']",
      },
    ],
  },
  {
    id: 'unicorn',
    sourceModulePath: 'packages/eslint-config/src/configs/unicorn.ts',
    sourceExportName: 'unicorn',
    targetFilePath: 'packages/oxlint-config/src/configs/unicorn.ts',
    targetExportName: 'unicorn',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'unicorn',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/unicorn/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['unicorn']",
      },
    ],
  },
  {
    id: 'typescript',
    sourceModulePath: 'packages/eslint-config/src/configs/typescript.ts',
    sourceExportName: 'typescript',
    targetFilePath: 'packages/oxlint-config/src/configs/typescript.ts',
    targetExportName: 'typescript',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'typescript',
    remapRuleName: createPrefixRemapper('@typescript-eslint/', 'typescript/'),
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/typescript/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['typescript']",
      },
      {
        sourceConfigNames: ['nelsonlaidev/typescript/declarations'],
        filesExpression: "['**/*.d.ts']",
        pluginsExpression: "['typescript']",
        commentByRuleName: {
          'typescript/consistent-type-definitions': [
            '// We sometimes need to use `interface` in declaration files,',
            '// especially when we want to extend from a type from another package,',
            '// and that type is an interface.',
          ],
          'typescript/consistent-indexed-object-style': [
            '// Similar to the above rule, interfaces support index signatures only when',
            '// we define object types with them.',
          ],
        },
        preserveOffRules: true,
      },
    ],
  },
  {
    id: 'import',
    sourceModulePath: 'packages/eslint-config/src/configs/import-x.ts',
    sourceExportName: 'importX',
    targetFilePath: 'packages/oxlint-config/src/configs/imports.ts',
    targetExportName: 'imports',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'import',
    remapRuleName: createPrefixRemapper('import-x/', 'import/'),
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/import-x/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['import']",
      },
    ],
  },
  {
    id: 'jsdoc',
    sourceModulePath: 'packages/eslint-config/src/configs/jsdoc.ts',
    sourceExportName: 'jsdoc',
    targetFilePath: 'packages/oxlint-config/src/configs/jsdoc.ts',
    targetExportName: 'jsdoc',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'jsdoc',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/jsdoc/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['jsdoc']",
      },
    ],
  },
  {
    id: 'vitest',
    sourceModulePath: 'packages/eslint-config/src/configs/vitest.ts',
    sourceExportName: 'vitest',
    sourceArgs: [{ files: ['__SYNC_PLACEHOLDER__'] }],
    targetFilePath: 'packages/oxlint-config/src/configs/vitest.ts',
    targetExportName: 'vitest',
    functionSignature: '(config: VitestConfig): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", "import type { VitestConfig } from '../types/vitest'"],
    oxlintScope: 'vitest',
    oxlintFallbackScopes: ['jest'],
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/vitest/rules'],
        filesExpression: 'config.files',
        pluginsExpression: "['vitest', 'jest']",
      },
    ],
  },
  {
    id: 'jsx-a11y',
    sourceModulePath: 'packages/eslint-config/src/configs/jsx-a11y.ts',
    sourceExportName: 'jsxA11y',
    targetFilePath: 'packages/oxlint-config/src/configs/jsx-a11y.ts',
    targetExportName: 'jsxA11y',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'jsx_a11y',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/jsx-a11y/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['jsx-a11y']",
      },
    ],
  },
  {
    id: 'nextjs',
    sourceModulePath: 'packages/eslint-config/src/configs/nextjs.ts',
    sourceExportName: 'nextjs',
    targetFilePath: 'packages/oxlint-config/src/configs/nextjs.ts',
    targetExportName: 'nextjs',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'nextjs',
    remapRuleName: createPrefixRemapper('@next/next/', 'nextjs/'),
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/nextjs/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['nextjs']",
      },
    ],
  },
  {
    id: 'promise',
    sourceModulePath: 'packages/eslint-config/src/configs/promise.ts',
    sourceExportName: 'promise',
    targetFilePath: 'packages/oxlint-config/src/configs/promise.ts',
    targetExportName: 'promise',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'promise',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/promise/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['promise']",
      },
    ],
  },
  {
    id: 'node',
    sourceModulePath: 'packages/eslint-config/src/configs/node.ts',
    sourceExportName: 'node',
    targetFilePath: 'packages/oxlint-config/src/configs/node.ts',
    targetExportName: 'node',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'node',
    remapRuleName: createPrefixRemapper('n/', 'node/'),
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/node/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['node']",
      },
    ],
  },
]

export function readRulesFromCommand(): OxlintRule[] {
  const oxlintOutput = execSync(`pnpm -C packages/oxlint-config exec oxlint --rules --format=json`, {
    cwd: ROOT_DIR,
    encoding: 'utf-8',
    stdio: 'pipe',
  })

  return JSON.parse(oxlintOutput) as OxlintRule[]
}

export function buildSupportedRuleLookup(rules: OxlintRule[]): RuleLookup {
  const lookup = new Map<string, Set<string>>()

  for (const rule of rules) {
    const supportedRules = lookup.get(rule.scope) ?? new Set<string>()
    supportedRules.add(rule.value)
    lookup.set(rule.scope, supportedRules)
  }

  return lookup
}

export function normalizeRuleValue(rawValue: unknown): SyncedRuleValue {
  if (Array.isArray(rawValue)) {
    const [level, ...options] = rawValue as readonly unknown[]
    const normalizedLevel = normalizeSeverity(level)

    if (normalizedLevel === 'off') {
      return 'off'
    }

    return options.length === 0 ? 'error' : ['error', ...options]
  }

  return normalizeSeverity(rawValue)
}

function normalizeSeverity(level: unknown): 'error' | 'off' {
  if (level === 'off' || level === 0) {
    return 'off'
  }

  if (level === 'warn' || level === 1 || level === 'error' || level === 2) {
    return 'error'
  }

  throw new Error(`Unsupported ESLint rule severity: ${JSON.stringify(level)}`)
}

function resolveFromRoot(filePath: string) {
  return path.join(ROOT_DIR, filePath)
}

async function loadSourceConfigs(entry: PresetManifestEntry): Promise<EslintFlatConfig[]> {
  const moduleUrl = pathToFileURL(resolveFromRoot(entry.sourceModulePath)).href
  const sourceModule = (await import(moduleUrl)) as Record<string, (...args: unknown[]) => EslintFlatConfig[]>
  const sourceFactory = sourceModule[entry.sourceExportName]

  if (typeof sourceFactory !== 'function') {
    throw new TypeError(`Missing source export "${entry.sourceExportName}" in ${entry.sourceModulePath}`)
  }

  return sourceFactory(...(entry.sourceArgs ?? []))
}

function getConfigByName(configs: EslintFlatConfig[], configName: string): EslintFlatConfig {
  const config = configs.find((item) => item.name === configName)

  if (!config) {
    throw new Error(`Unable to find ESLint config "${configName}"`)
  }

  return config
}

export function collectRulesForGroup(configs: EslintFlatConfig[], group: RuleGroupManifest): Record<string, unknown> {
  const collectedRules: Record<string, unknown> = {}

  for (const configName of group.sourceConfigNames) {
    const config = getConfigByName(configs, configName)
    Object.assign(collectedRules, config.rules)
  }

  return collectedRules
}

function getScopedRuleValue(ruleName: string) {
  const slashIndex = ruleName.indexOf('/')
  return slashIndex === -1 ? ruleName : ruleName.slice(slashIndex + 1)
}

export function mapToSupportedOxlintRules(
  rules: Record<string, unknown>,
  entry: Pick<PresetManifestEntry, 'oxlintScope' | 'oxlintFallbackScopes' | 'remapRuleName'>,
  supportedRules: RuleLookup,
  { preserveOffRules = false }: { preserveOffRules?: boolean } = {},
): Record<string, SyncedRuleValue> {
  const syncedRules = new Map<string, SyncedRuleValue>()

  for (const [eslintRuleName, rawValue] of Object.entries(rules)) {
    const normalizedValue = normalizeRuleValue(rawValue)

    if (normalizedValue === 'off' && !preserveOffRules) {
      continue
    }

    const remappedRuleName = entry.remapRuleName(eslintRuleName)

    if (!remappedRuleName) {
      continue
    }

    const oxlintRuleName = resolveSupportedOxlintRuleName(remappedRuleName, entry, supportedRules)

    if (!oxlintRuleName) {
      continue
    }

    syncedRules.set(oxlintRuleName, normalizedValue)
  }

  return Object.fromEntries(
    syncedRules
      .entries()
      .toArray()
      .toSorted(([left], [right]) => left.localeCompare(right)),
  )
}

function resolveSupportedOxlintRuleName(
  ruleName: string,
  entry: Pick<PresetManifestEntry, 'oxlintScope' | 'oxlintFallbackScopes'>,
  supportedRules: RuleLookup,
) {
  const ruleValue = getScopedRuleValue(ruleName)

  if (supportedRules.get(entry.oxlintScope)?.has(ruleValue)) {
    return ruleName
  }

  for (const fallbackScope of entry.oxlintFallbackScopes ?? []) {
    if (supportedRules.get(fallbackScope)?.has(ruleValue)) {
      return `${fallbackScope}/${ruleValue}`
    }
  }

  return null
}

function renderRuleEntries(rules: Record<string, SyncedRuleValue>, comments: Record<string, string[]> = {}) {
  const lines: string[] = []

  for (const [ruleName, value] of Object.entries(rules)) {
    for (const commentLine of comments[ruleName] ?? []) {
      lines.push(`      ${commentLine}`)
    }

    const renderedEntry = JSON.stringify({ [ruleName]: value }, null, 2)
      .split('\n')
      .slice(1, -1)
      .map((line) => `    ${line}`)

    const lastIndex = renderedEntry.length - 1

    if (lastIndex < 0) {
      continue
    }

    renderedEntry[lastIndex] = `${renderedEntry[lastIndex]},`
    lines.push(...renderedEntry)
  }

  return lines
}

function renderRulesObject(rules: Record<string, SyncedRuleValue>, comments?: Record<string, string[]>) {
  const renderedEntries = renderRuleEntries(rules, comments)

  if (renderedEntries.length === 0) {
    return '    rules: {},'
  }

  return ['    rules: {', ...renderedEntries, '    },'].join('\n')
}

function renderOverride(group: RuleGroupManifest, rules: Record<string, SyncedRuleValue>) {
  return [
    '  {',
    `    files: ${group.filesExpression},`,
    `    plugins: ${group.pluginsExpression},`,
    renderRulesObject(rules, group.commentByRuleName),
    '  }',
  ].join('\n')
}

async function formatGeneratedSource(source: string, targetFilePath: string) {
  const absoluteTargetPath = resolveFromRoot(targetFilePath)
  const prettierConfig = (await resolveConfig(absoluteTargetPath)) ?? {}
  return format(source, {
    ...prettierConfig,
    filepath: absoluteTargetPath,
    parser: 'typescript',
  })
}

export async function generatePresetContent(entry: PresetManifestEntry, supportedRules: RuleLookup): Promise<string> {
  const sourceConfigs = await loadSourceConfigs(entry)
  const renderedOverrides = entry.groups.map((group) => {
    const eslintRules = collectRulesForGroup(sourceConfigs, group)
    const syncedRules = mapToSupportedOxlintRules(eslintRules, entry, supportedRules, {
      preserveOffRules: group.preserveOffRules,
    })
    return renderOverride(group, syncedRules)
  })

  const source = [
    GENERATED_HEADER,
    '',
    ...entry.imports,
    '',
    `export const ${entry.targetExportName} = ${entry.functionSignature} => [`,
    renderedOverrides.join(',\n'),
    ']',
    '',
  ].join('\n')

  return formatGeneratedSource(source, entry.targetFilePath)
}

export async function generatePresetOutputs(supportedRules: RuleLookup) {
  return Promise.all(
    PRESET_MANIFEST.map(async (entry) => ({
      entry,
      content: await generatePresetContent(entry, supportedRules),
    })),
  )
}

export async function syncOxlintEslint({ check = false }: { check?: boolean } = {}): Promise<SyncResult> {
  const supportedRules = buildSupportedRuleLookup(readRulesFromCommand())
  const presetOutputs = await generatePresetOutputs(supportedRules)

  const staleFilePaths: string[] = []
  const updatedFilePaths: string[] = []

  for (const { entry, content } of presetOutputs) {
    const absoluteTargetPath = resolveFromRoot(entry.targetFilePath)
    const currentContent = readFileSync(absoluteTargetPath, 'utf-8')

    if (currentContent === content) {
      continue
    }

    staleFilePaths.push(absoluteTargetPath)

    if (!check) {
      writeFileSync(absoluteTargetPath, content)
      updatedFilePaths.push(absoluteTargetPath)
    }
  }

  return { staleFilePaths, updatedFilePaths }
}

async function main() {
  const check = process.argv.includes('--check')
  const result = await syncOxlintEslint({ check })

  if (check && result.staleFilePaths.length > 0) {
    console.error('Oxlint preset files are out of sync:')

    for (const filePath of result.staleFilePaths) {
      console.error(`- ${path.relative(ROOT_DIR, filePath)}`)
    }

    process.exitCode = 1
    return
  }

  if (check) {
    console.log('Oxlint preset files are in sync.')
    return
  }

  if (result.updatedFilePaths.length === 0) {
    console.log('Oxlint preset files are already up to date.')
    return
  }

  console.log(`Updated ${result.updatedFilePaths.length} Oxlint preset file(s):`)

  for (const filePath of result.updatedFilePaths) {
    console.log(`- ${path.relative(ROOT_DIR, filePath)}`)
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main()
}
