// Inspired by @oxlint/migrate
// https://github.com/oxc-project/oxlint-migrate/blob/5e7463f9cc49d1074efe2230264b0068cb89ecfc/scripts/traverse-rules.ts

import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { format, resolveConfig } from 'prettier'

type OxlintRule = {
  value: string
  scope: string
  category: string
  type_aware: boolean
  fix?: string
  default?: boolean
  docs_url?: string
}

type EslintFlatConfig = {
  name?: string
  rules?: Record<string, unknown>
}

type EnabledRuleValue = 'error' | ['error', ...unknown[]]
type SyncedRuleValue = 'off' | EnabledRuleValue

type RuleLookup = Map<string, Set<string>>

type RuleGroupManifest = {
  sourceConfigNames: string[]
  filesExpression: string
  pluginsExpression: string
  commentByRuleName?: Record<string, string[]>
  preserveOffRules?: boolean
  dropRuleOptions?: string[]
  augmentRuleOptions?: Record<string, Record<string, unknown>>
}

type PresetManifestEntry = {
  id: string
  sourceModulePath: string
  sourceExportName: string
  sourceArgs?: unknown[]
  targetFilePath: string
  targetExportName: string
  targetArgs?: unknown[]
  functionSignature: string
  imports: string[]
  oxlintScope: string
  oxlintFallbackScopes?: string[]
  remapRuleName: (ruleName: string) => string | null
  groups: RuleGroupManifest[]
}

type DiffOnlyManifestEntry = {
  id: string
  sourceModulePath: string
  sourceExportName: string
  sourceArgs?: unknown[]
  targetFilePath: string
  targetExportName: string
  targetArgs?: unknown[]
  remapRuleName: (ruleName: string) => string | null
  groups: Array<Pick<RuleGroupManifest, 'sourceConfigNames'>>
}

type SyncResult = {
  staleFilePaths: string[]
  updatedFilePaths: string[]
}

type MigrationGap = {
  ruleName: string
  reason: 'off' | 'not_remapped' | 'not_supported'
}

type MigrationGroupReport = {
  sourceConfigNames: string[]
  total: number
  synced: number
  unsupported: MigrationGap[]
}

type MigrationPresetReport = {
  id: string
  groups: MigrationGroupReport[]
}

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const GENERATED_HEADER = [
  '// This file is generated by `scripts/sync-oxlint-eslint.ts`.',
  '// Do not edit this file manually.',
].join('\n')

function identityRemapper(ruleName: string) {
  return ruleName
}

function createPrefixRemapper(from: string, to: string) {
  return (ruleName: string) => (ruleName.startsWith(from) ? `${to}${ruleName.slice(from.length)}` : null)
}

export const PRESET_MANIFEST: PresetManifestEntry[] = [
  {
    id: 'eslint',
    sourceModulePath: 'packages/eslint-config/src/configs/javascript.ts',
    sourceExportName: 'javascript',
    targetFilePath: 'packages/oxlint-config/src/configs/eslint.ts',
    targetExportName: 'eslint',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'eslint',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/javascript/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['eslint']",
        augmentRuleOptions: {
          'no-unused-vars': { fix: { imports: 'safe-fix' } },
        },
      },
    ],
  },
  {
    id: 'unicorn',
    sourceModulePath: 'packages/eslint-config/src/configs/unicorn.ts',
    sourceExportName: 'unicorn',
    targetFilePath: 'packages/oxlint-config/src/configs/unicorn.ts',
    targetExportName: 'unicorn',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'unicorn',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/unicorn/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['unicorn']",
      },
    ],
  },
  {
    id: 'typescript',
    sourceModulePath: 'packages/eslint-config/src/configs/typescript.ts',
    sourceExportName: 'typescript',
    targetFilePath: 'packages/oxlint-config/src/configs/typescript.ts',
    targetExportName: 'typescript',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'typescript',
    remapRuleName: createPrefixRemapper('@typescript-eslint/', 'typescript/'),
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/typescript/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['typescript']",
      },
      {
        sourceConfigNames: ['nelsonlaidev/typescript/declarations'],
        filesExpression: "['**/*.d.ts']",
        pluginsExpression: "['typescript']",
        commentByRuleName: {
          'typescript/consistent-type-definitions': [
            '// We sometimes need to use `interface` in declaration files,',
            '// especially when we want to extend from a type from another package,',
            '// and that type is an interface.',
          ],
          'typescript/consistent-indexed-object-style': [
            '// Similar to the above rule, interfaces support index signatures only when',
            '// we define object types with them.',
          ],
        },
        preserveOffRules: true,
      },
    ],
  },
  {
    id: 'import',
    sourceModulePath: 'packages/eslint-config/src/configs/import-x.ts',
    sourceExportName: 'importX',
    targetFilePath: 'packages/oxlint-config/src/configs/imports.ts',
    targetExportName: 'imports',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'import',
    remapRuleName: createPrefixRemapper('import-x/', 'import/'),
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/import-x/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['import']",
      },
    ],
  },
  {
    id: 'jsdoc',
    sourceModulePath: 'packages/eslint-config/src/configs/jsdoc.ts',
    sourceExportName: 'jsdoc',
    targetFilePath: 'packages/oxlint-config/src/configs/jsdoc.ts',
    targetExportName: 'jsdoc',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'jsdoc',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/jsdoc/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['jsdoc']",
      },
    ],
  },
  {
    id: 'vitest',
    sourceModulePath: 'packages/eslint-config/src/configs/vitest.ts',
    sourceExportName: 'vitest',
    sourceArgs: [{ files: ['__SYNC_PLACEHOLDER__'] }],
    targetFilePath: 'packages/oxlint-config/src/configs/vitest.ts',
    targetExportName: 'vitest',
    targetArgs: [{ files: ['**/*.test.ts'] }],
    functionSignature: '(config: VitestConfig): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", "import type { VitestConfig } from '../types/vitest'"],
    oxlintScope: 'vitest',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/vitest/rules'],
        filesExpression: 'config.files',
        pluginsExpression: "['vitest']",
      },
    ],
  },
  {
    id: 'jsx-a11y',
    sourceModulePath: 'packages/eslint-config/src/configs/jsx-a11y.ts',
    sourceExportName: 'jsxA11y',
    targetFilePath: 'packages/oxlint-config/src/configs/jsx-a11y.ts',
    targetExportName: 'jsxA11y',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'jsx_a11y',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/jsx-a11y/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['jsx-a11y']",
      },
    ],
  },
  {
    id: 'nextjs',
    sourceModulePath: 'packages/eslint-config/src/configs/nextjs.ts',
    sourceExportName: 'nextjs',
    targetFilePath: 'packages/oxlint-config/src/configs/nextjs.ts',
    targetExportName: 'nextjs',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'nextjs',
    remapRuleName: createPrefixRemapper('@next/next/', 'nextjs/'),
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/nextjs/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['nextjs']",
      },
    ],
  },
  {
    id: 'promise',
    sourceModulePath: 'packages/eslint-config/src/configs/promise.ts',
    sourceExportName: 'promise',
    targetFilePath: 'packages/oxlint-config/src/configs/promise.ts',
    targetExportName: 'promise',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'promise',
    remapRuleName: identityRemapper,
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/promise/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['promise']",
      },
    ],
  },
  {
    id: 'node',
    sourceModulePath: 'packages/eslint-config/src/configs/node.ts',
    sourceExportName: 'node',
    targetFilePath: 'packages/oxlint-config/src/configs/node.ts',
    targetExportName: 'node',
    functionSignature: '(): OxlintOverride[]',
    imports: ["import type { OxlintOverride } from 'oxlint'", '', "import { GLOB_SRC } from '../globs'"],
    oxlintScope: 'node',
    remapRuleName: createPrefixRemapper('n/', 'node/'),
    groups: [
      {
        sourceConfigNames: ['nelsonlaidev/node/rules'],
        filesExpression: '[GLOB_SRC]',
        pluginsExpression: "['node']",
      },
    ],
  },
]

export const MANUAL_DIFF_MANIFEST: DiffOnlyManifestEntry[] = [
  {
    id: 'regexp',
    sourceModulePath: 'packages/eslint-config/src/configs/regexp.ts',
    sourceExportName: 'regexp',
    targetFilePath: 'packages/oxlint-config/src/configs/regexp.ts',
    targetExportName: 'regexp',
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/regexp/rules'] }],
  },
  {
    id: 'playwright',
    sourceModulePath: 'packages/eslint-config/src/configs/playwright.ts',
    sourceExportName: 'playwright',
    sourceArgs: [{ files: ['__DIFF_PLACEHOLDER__'] }],
    targetFilePath: 'packages/oxlint-config/src/configs/playwright.ts',
    targetExportName: 'playwright',
    targetArgs: [{ files: ['__DIFF_PLACEHOLDER__'] }],
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/playwright/rules'] }],
  },
  {
    id: 'sonarjs',
    sourceModulePath: 'packages/eslint-config/src/configs/sonarjs.ts',
    sourceExportName: 'sonarjs',
    targetFilePath: 'packages/oxlint-config/src/configs/sonarjs.ts',
    targetExportName: 'sonarjs',
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/sonarjs/rules'] }],
  },
  {
    id: 'zod',
    sourceModulePath: 'packages/eslint-config/src/configs/zod.ts',
    sourceExportName: 'zod',
    targetFilePath: 'packages/oxlint-config/src/configs/zod.ts',
    targetExportName: 'zod',
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/zod/rules'] }],
  },
  {
    id: 'stylistic',
    sourceModulePath: 'packages/eslint-config/src/configs/stylistic.ts',
    sourceExportName: 'stylistic',
    targetFilePath: 'packages/oxlint-config/src/configs/stylistic.ts',
    targetExportName: 'stylistic',
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/stylistic/rules'] }],
  },
  {
    id: 'de-morgan',
    sourceModulePath: 'packages/eslint-config/src/configs/de-morgan.ts',
    sourceExportName: 'deMorgan',
    targetFilePath: 'packages/oxlint-config/src/configs/de-morgan.ts',
    targetExportName: 'deMorgan',
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/de-morgan/rules'] }],
  },
  {
    id: 'tailwindcss',
    sourceModulePath: 'packages/eslint-config/src/configs/tailwindcss.ts',
    sourceExportName: 'tailwindcss',
    sourceArgs: [{}],
    targetFilePath: 'packages/oxlint-config/src/configs/tailwindcss.ts',
    targetExportName: 'tailwindcss',
    targetArgs: [{}],
    remapRuleName: identityRemapper,
    groups: [{ sourceConfigNames: ['nelsonlaidev/tailwindcss/rules'] }],
  },
  {
    id: 'react',
    sourceModulePath: 'packages/eslint-config/src/configs/react.ts',
    sourceExportName: 'react',
    targetFilePath: 'packages/oxlint-config/src/configs/react.ts',
    targetExportName: 'react',
    remapRuleName: (ruleName) =>
      ruleName.startsWith('react-hooks/') ? `react-hooks-js/${ruleName.slice('react-hooks/'.length)}` : ruleName,
    groups: [{ sourceConfigNames: ['nelsonlaidev/react/rules'] }],
  },
  {
    id: 'nelsonlaidev',
    sourceModulePath: 'packages/eslint-config/src/configs/nelsonlaidev.ts',
    sourceExportName: 'nelsonlaidev',
    targetFilePath: 'packages/oxlint-config/src/configs/nelsonlaidev.ts',
    targetExportName: 'nelsonlaidev',
    remapRuleName: createPrefixRemapper('@nelsonlaidev/', 'nelsonlaidev/'),
    groups: [{ sourceConfigNames: ['nelsonlaidev/nelsonlaidev/rules'] }],
  },
]

export function readRulesFromCommand(): OxlintRule[] {
  const oxlintOutput = execSync(`pnpm -C packages/oxlint-config exec oxlint --rules --format=json`, {
    cwd: ROOT_DIR,
    encoding: 'utf-8',
    stdio: 'pipe',
  })

  return JSON.parse(oxlintOutput) as OxlintRule[]
}

export function buildSupportedRuleLookup(rules: OxlintRule[]): RuleLookup {
  const lookup = new Map<string, Set<string>>()

  for (const rule of rules) {
    const supportedRules = lookup.get(rule.scope) ?? new Set<string>()
    supportedRules.add(rule.value)
    lookup.set(rule.scope, supportedRules)
  }

  return lookup
}

export function buildDefaultEnabledRuleLookup(rules: OxlintRule[]): RuleLookup {
  const lookup = new Map<string, Set<string>>()

  for (const rule of rules) {
    if (rule.category !== 'correctness') continue

    const defaultRules = lookup.get(rule.scope) ?? new Set<string>()
    defaultRules.add(rule.value)
    lookup.set(rule.scope, defaultRules)
  }

  return lookup
}

function scopeToPluginName(scope: string): string {
  if (scope === 'jsx_a11y') return 'jsx-a11y'
  return scope
}

export function normalizeRuleValue(rawValue: unknown): SyncedRuleValue {
  if (Array.isArray(rawValue)) {
    const [level, ...options] = rawValue as readonly unknown[]
    const normalizedLevel = normalizeSeverity(level)

    if (normalizedLevel === 'off') {
      return 'off'
    }

    return options.length === 0 ? 'error' : ['error', ...options]
  }

  return normalizeSeverity(rawValue)
}

function normalizeRules(rules: Record<string, unknown>): Record<string, SyncedRuleValue> {
  const result: Record<string, SyncedRuleValue> = {}
  for (const [key, value] of Object.entries(rules)) {
    result[key] = normalizeRuleValue(value)
  }
  return result
}

function normalizeSeverity(level: unknown): 'error' | 'off' {
  if (level === 'off' || level === 0) {
    return 'off'
  }

  if (level === 'warn' || level === 1 || level === 'error' || level === 2) {
    return 'error'
  }

  throw new Error(`Unsupported ESLint rule severity: ${JSON.stringify(level)}`)
}

function resolveFromRoot(filePath: string) {
  return path.join(ROOT_DIR, filePath)
}

async function loadSourceConfigs(entry: PresetManifestEntry): Promise<EslintFlatConfig[]> {
  const moduleUrl = pathToFileURL(resolveFromRoot(entry.sourceModulePath)).href
  const sourceModule = (await import(moduleUrl)) as Record<string, (...args: unknown[]) => EslintFlatConfig[]>
  const sourceFactory = sourceModule[entry.sourceExportName]

  if (typeof sourceFactory !== 'function') {
    throw new TypeError(`Missing source export "${entry.sourceExportName}" in ${entry.sourceModulePath}`)
  }

  return sourceFactory(...(entry.sourceArgs ?? []))
}

function getConfigByName(configs: EslintFlatConfig[], configName: string): EslintFlatConfig {
  const config = configs.find((item) => item.name === configName)

  if (!config) {
    throw new Error(`Unable to find ESLint config "${configName}"`)
  }

  return config
}

export function collectRulesForGroup(configs: EslintFlatConfig[], group: RuleGroupManifest): Record<string, unknown> {
  const collectedRules: Record<string, unknown> = {}

  for (const configName of group.sourceConfigNames) {
    const config = getConfigByName(configs, configName)
    Object.assign(collectedRules, config.rules)
  }

  return collectedRules
}

function getScopedRuleValue(ruleName: string) {
  const slashIndex = ruleName.indexOf('/')
  return slashIndex === -1 ? ruleName : ruleName.slice(slashIndex + 1)
}

export function mapToSupportedOxlintRules(
  rules: Record<string, unknown>,
  entry: Pick<PresetManifestEntry, 'oxlintScope' | 'oxlintFallbackScopes' | 'remapRuleName'>,
  supportedRules: RuleLookup,
  {
    preserveOffRules = false,
    dropRuleOptions = [],
    augmentRuleOptions = {},
  }: {
    preserveOffRules?: boolean
    dropRuleOptions?: string[]
    augmentRuleOptions?: Record<string, Record<string, unknown>>
  } = {},
  defaultEnabledRules?: RuleLookup,
): Record<string, SyncedRuleValue> {
  const dropSet = new Set(dropRuleOptions)
  const syncedRules = new Map<string, SyncedRuleValue>()

  for (const [eslintRuleName, rawValue] of Object.entries(rules)) {
    const normalizedValue = normalizeRuleValue(rawValue)

    if (normalizedValue === 'off' && !preserveOffRules) {
      continue
    }

    const remappedRuleName = entry.remapRuleName(eslintRuleName)

    if (!remappedRuleName) {
      continue
    }

    const oxlintRuleName = resolveSupportedOxlintRuleName(remappedRuleName, entry, supportedRules)

    if (!oxlintRuleName) {
      continue
    }

    let finalValue: SyncedRuleValue =
      dropSet.has(oxlintRuleName) && normalizedValue !== 'off' ? 'error' : normalizedValue

    const augment = augmentRuleOptions[oxlintRuleName]
    if (augment && finalValue !== 'off') {
      const existingOptions = Array.isArray(finalValue) ? finalValue.slice(1) : []
      finalValue = ['error', ...existingOptions, augment]
    }

    syncedRules.set(oxlintRuleName, finalValue)
  }

  if (defaultEnabledRules && !preserveOffRules) {
    const scopeDefaults = defaultEnabledRules.get(entry.oxlintScope)
    if (scopeDefaults) {
      for (const ruleValue of scopeDefaults) {
        if (!supportedRules.get(entry.oxlintScope)?.has(ruleValue)) continue

        // eslint core rules may use unprefixed names; check both formats
        const prefixedName = `${scopeToPluginName(entry.oxlintScope)}/${ruleValue}`
        if (syncedRules.has(prefixedName) || syncedRules.has(ruleValue)) continue

        // eslint core scope uses unprefixed names, other scopes use prefixed
        const name = entry.oxlintScope === 'eslint' ? ruleValue : prefixedName
        syncedRules.set(name, 'off')
      }
    }
  }

  return Object.fromEntries(
    syncedRules
      .entries()
      .toArray()
      .toSorted(([left], [right]) => left.localeCompare(right)),
  )
}

export function analyzeGroupMigration(
  rules: Record<string, unknown>,
  entry: Pick<PresetManifestEntry, 'oxlintScope' | 'oxlintFallbackScopes' | 'remapRuleName'>,
  supportedRules: RuleLookup,
  { preserveOffRules = false }: { preserveOffRules?: boolean } = {},
): { synced: string[]; unsupported: MigrationGap[] } {
  const synced: string[] = []
  const unsupported: MigrationGap[] = []

  for (const [eslintRuleName, rawValue] of Object.entries(rules)) {
    const normalizedValue = normalizeRuleValue(rawValue)

    if (normalizedValue === 'off' && !preserveOffRules) {
      continue
    }

    const remappedRuleName = entry.remapRuleName(eslintRuleName)

    if (!remappedRuleName) {
      unsupported.push({ ruleName: eslintRuleName, reason: 'not_remapped' })
      continue
    }

    const oxlintRuleName = resolveSupportedOxlintRuleName(remappedRuleName, entry, supportedRules)

    if (!oxlintRuleName) {
      unsupported.push({ ruleName: eslintRuleName, reason: 'not_supported' })
      continue
    }

    synced.push(oxlintRuleName)
  }

  return { synced, unsupported }
}

function resolveSupportedOxlintRuleName(
  ruleName: string,
  entry: Pick<PresetManifestEntry, 'oxlintScope' | 'oxlintFallbackScopes'>,
  supportedRules: RuleLookup,
) {
  const ruleValue = getScopedRuleValue(ruleName)

  if (supportedRules.get(entry.oxlintScope)?.has(ruleValue)) {
    return ruleName
  }

  for (const fallbackScope of entry.oxlintFallbackScopes ?? []) {
    if (supportedRules.get(fallbackScope)?.has(ruleValue)) {
      return `${fallbackScope}/${ruleValue}`
    }
  }

  return null
}

function renderRuleEntries(rules: Record<string, SyncedRuleValue>, comments: Record<string, string[]> = {}) {
  const lines: string[] = []

  for (const [ruleName, value] of Object.entries(rules)) {
    for (const commentLine of comments[ruleName] ?? []) {
      lines.push(`      ${commentLine}`)
    }

    const renderedEntry = JSON.stringify({ [ruleName]: value }, null, 2)
      .split('\n')
      .slice(1, -1)
      .map((line) => `    ${line}`)

    const lastIndex = renderedEntry.length - 1

    if (lastIndex < 0) {
      continue
    }

    renderedEntry[lastIndex] = `${renderedEntry[lastIndex]},`
    lines.push(...renderedEntry)
  }

  return lines
}

function renderRulesObject(rules: Record<string, SyncedRuleValue>, comments?: Record<string, string[]>) {
  const renderedEntries = renderRuleEntries(rules, comments)

  if (renderedEntries.length === 0) {
    return '    rules: {},'
  }

  return ['    rules: {', ...renderedEntries, '    },'].join('\n')
}

function renderOverride(group: RuleGroupManifest, rules: Record<string, SyncedRuleValue>) {
  return [
    '  {',
    `    files: ${group.filesExpression},`,
    `    plugins: ${group.pluginsExpression},`,
    renderRulesObject(rules, group.commentByRuleName),
    '  }',
  ].join('\n')
}

async function formatGeneratedSource(source: string, targetFilePath: string) {
  const absoluteTargetPath = resolveFromRoot(targetFilePath)
  const prettierConfig = (await resolveConfig(absoluteTargetPath)) ?? {}
  return format(source, {
    ...prettierConfig,
    filepath: absoluteTargetPath,
    parser: 'typescript',
  })
}

export async function generatePresetContent(
  entry: PresetManifestEntry,
  supportedRules: RuleLookup,
  defaultEnabledRules?: RuleLookup,
): Promise<string> {
  const sourceConfigs = await loadSourceConfigs(entry)
  const renderedOverrides = entry.groups.map((group) => {
    const eslintRules = collectRulesForGroup(sourceConfigs, group)
    const syncedRules = mapToSupportedOxlintRules(
      eslintRules,
      entry,
      supportedRules,
      {
        preserveOffRules: group.preserveOffRules,
        dropRuleOptions: group.dropRuleOptions,
        augmentRuleOptions: group.augmentRuleOptions,
      },
      defaultEnabledRules,
    )
    return renderOverride(group, syncedRules)
  })

  const source = [
    GENERATED_HEADER,
    '',
    ...entry.imports,
    '',
    `export const ${entry.targetExportName} = ${entry.functionSignature} => [`,
    renderedOverrides.join(',\n'),
    ']',
    '',
  ].join('\n')

  return formatGeneratedSource(source, entry.targetFilePath)
}

export async function generatePresetOutputs(supportedRules: RuleLookup, defaultEnabledRules?: RuleLookup) {
  return Promise.all(
    PRESET_MANIFEST.map(async (entry) => ({
      entry,
      content: await generatePresetContent(entry, supportedRules, defaultEnabledRules),
    })),
  )
}

export async function syncOxlintEslint({ check = false }: { check?: boolean } = {}): Promise<SyncResult> {
  const rules = readRulesFromCommand()
  const supportedRules = buildSupportedRuleLookup(rules)
  const defaultEnabledRules = buildDefaultEnabledRuleLookup(rules)
  const presetOutputs = await generatePresetOutputs(supportedRules, defaultEnabledRules)

  const staleFilePaths: string[] = []
  const updatedFilePaths: string[] = []

  for (const { entry, content } of presetOutputs) {
    const absoluteTargetPath = resolveFromRoot(entry.targetFilePath)
    const currentContent = readFileSync(absoluteTargetPath, 'utf-8')

    if (currentContent === content) {
      continue
    }

    staleFilePaths.push(absoluteTargetPath)

    if (!check) {
      writeFileSync(absoluteTargetPath, content)
      updatedFilePaths.push(absoluteTargetPath)
    }
  }

  return { staleFilePaths, updatedFilePaths }
}

export async function generateMigrationReport(supportedRules: RuleLookup): Promise<MigrationPresetReport[]> {
  const allSourceConfigs = await Promise.all(PRESET_MANIFEST.map(async (entry) => loadSourceConfigs(entry)))

  return PRESET_MANIFEST.map((entry, index) => {
    const sourceConfigs = allSourceConfigs[index]
    if (!sourceConfigs) {
      throw new Error(`Missing source configs for preset "${entry.id}"`)
    }
    const groupReports: MigrationGroupReport[] = entry.groups.map((group) => {
      const eslintRules = collectRulesForGroup(sourceConfigs, group)
      const { synced, unsupported } = analyzeGroupMigration(eslintRules, entry, supportedRules, {
        preserveOffRules: group.preserveOffRules,
      })

      return {
        sourceConfigNames: group.sourceConfigNames,
        total: synced.length + unsupported.length,
        synced: synced.length,
        unsupported,
      }
    })

    return { id: entry.id, groups: groupReports }
  })
}

export function printMigrationReport(reports: MigrationPresetReport[]) {
  const notSupportedByGroup: Array<{ preset: string; rules: string[] }> = []

  for (const preset of reports) {
    for (const group of preset.groups) {
      const unsupported = group.unsupported.filter((g) => g.reason === 'not_supported')
      const pct = group.total > 0 ? ((group.synced / group.total) * 100).toFixed(1) : '0.0'
      const label = group.sourceConfigNames.join('+')

      console.log(`${preset.id}/${label}: ${group.synced}/${group.total} (${pct}%) synced`)

      if (unsupported.length > 0) {
        const ruleNames = unsupported.map((g) => g.ruleName)
        console.log(`  unsupported: ${ruleNames.join(', ')}`)
        notSupportedByGroup.push({ preset: preset.id, rules: ruleNames })
      }
    }
  }

  if (notSupportedByGroup.length > 0) {
    const totalUnsupported = notSupportedByGroup.reduce((sum, g) => sum + g.rules.length, 0)
    console.log(`\n${totalUnsupported} unsupported rule(s) across ${notSupportedByGroup.length} group(s).`)
  } else {
    console.log('\nAll rules are supported by oxlint.')
  }
}

const UNSCANNED_PLUGIN_TABLE = [
  '| Config | Reason |',
  '|--------|--------|',
  '| `command.ts` | Codemod for ESLint only, cannot be migrated |',
  '| `comments.ts` | Plugin that comments out eslint-disable directives |',
  '| `gitignore.ts` | File-based ignores, handled by Oxlint config |',
  '| `ignores.ts` | File ignore patterns |',
  '| `import-sort.ts` | Replaced by Oxlint built-in `import/sort` |',
  '| `prettier.ts` | Formatting concern, handled by oxfmt |',
  '  | `unused-imports.ts` | Replaced by Oxlint built-in `no-unused-vars` with `fix.imports` |',
].join('\n')

function formatMigrationTable(reports: MigrationPresetReport[]): string {
  const lines = ['| Preset | Synced | Total | Coverage |', '|--------|--------|-------|----------|']

  for (const preset of reports) {
    for (const group of preset.groups) {
      const pct = group.total > 0 ? ((group.synced / group.total) * 100).toFixed(1) : '0.0'
      const raw = group.sourceConfigNames[0] ?? ''
      const label = `${preset.id}/${raw.split('/').slice(1).join('/')}`

      lines.push(`| \`${label}\` | ${group.synced} | ${group.total} | ${pct}% |`)
    }
  }

  return lines.join('\n')
}

async function updateReadmeReport(supportedRules: RuleLookup) {
  const reports = await generateMigrationReport(supportedRules)
  const table = formatMigrationTable(reports)
  const readmePath = resolveFromRoot('packages/oxlint-config/README.md')
  const current = readFileSync(readmePath, 'utf-8')

  const startMarker = '<!-- sync:report-start -->'
  const endMarker = '<!-- sync:report-end -->'

  const startIndex = current.indexOf(startMarker)
  const endIndex = current.indexOf(endMarker)

  if (startIndex === -1 || endIndex === -1) {
    throw new Error(`Missing report markers (${startMarker} / ${endMarker}) in ${readmePath}`)
  }

  const content = [
    startMarker,
    '',
    '### Synced (auto-generated)',
    '',
    table,
    '',
    '### Manually maintained (diff-only)',
    '',
    'These use `jsPlugins` and are checked for consistency via `sync:check`.',
    '',
    MANUAL_DIFF_MANIFEST.map((e) => `- \`${e.id}\``).join('\n'),
    '',
    '### Unscanned ESLint plugins',
    '',
    UNSCANNED_PLUGIN_TABLE,
    '',
    endMarker,
  ].join('\n')

  const updated = current.slice(0, startIndex) + content + current.slice(endIndex + endMarker.length)

  const prettierConfig = (await resolveConfig(readmePath)) ?? {}
  const formatted = await format(updated, {
    ...prettierConfig,
    filepath: readmePath,
    parser: 'markdown',
  })

  writeFileSync(readmePath, formatted)
  console.log(`Updated ${path.relative(ROOT_DIR, readmePath)}`)
}

type OverrideLike = {
  files?: unknown
  plugins?: unknown
  jsPlugins?: unknown
  rules?: Record<string, unknown>
}

async function loadTargetOverrides(entry: PresetManifestEntry): Promise<OverrideLike[]> {
  const moduleUrl = `${pathToFileURL(resolveFromRoot(entry.targetFilePath)).href}?t=${Date.now()}`
  const targetModule = (await import(moduleUrl)) as Record<string, (...args: unknown[]) => unknown[]>
  const factory = targetModule[entry.targetExportName]

  if (typeof factory !== 'function') {
    throw new TypeError(`Missing target export "${entry.targetExportName}" in ${entry.targetFilePath}`)
  }

  return factory(...(entry.targetArgs ?? [])) as OverrideLike[]
}

type DiffGroupResult = {
  groupLabel: string
  added: string[]
  removed: string[]
  changed: string[]
}

async function diffPreset(
  entry: PresetManifestEntry,
  supportedRules: RuleLookup,
  defaultEnabledRules?: RuleLookup,
): Promise<DiffGroupResult[]> {
  const sourceConfigs = await loadSourceConfigs(entry)
  const targetOverrides = await loadTargetOverrides(entry)
  const results: DiffGroupResult[] = []

  let groupIndex = 0

  for (const group of entry.groups) {
    const eslintRules = collectRulesForGroup(sourceConfigs, group)
    const syncedRules = mapToSupportedOxlintRules(
      eslintRules,
      entry,
      supportedRules,
      {
        preserveOffRules: group.preserveOffRules,
        dropRuleOptions: group.dropRuleOptions,
        augmentRuleOptions: group.augmentRuleOptions,
      },
      defaultEnabledRules,
    )

    const targetRules = normalizeRules(targetOverrides[groupIndex]?.rules ?? {})

    const allKeys = new Set([...Object.keys(syncedRules), ...Object.keys(targetRules)])
    const added: string[] = []
    const removed: string[] = []
    const changed: string[] = []

    for (const key of allKeys) {
      const synced = JSON.stringify(syncedRules[key])
      const target = JSON.stringify(targetRules[key])

      if (synced === target) continue

      if (key in targetRules && key in syncedRules) {
        changed.push(key)
      } else if (key in targetRules) {
        removed.push(key)
      } else {
        added.push(key)
      }
    }

    results.push({
      groupLabel: group.sourceConfigNames.join('+'),
      added,
      removed,
      changed,
    })

    groupIndex += 1
  }

  return results
}

async function diffManualEntry(entry: DiffOnlyManifestEntry): Promise<DiffGroupResult[]> {
  const sourceConfigs = await loadSourceConfigs(entry as unknown as PresetManifestEntry)
  const targetOverrides = await loadTargetOverrides(entry as unknown as PresetManifestEntry)
  const results: DiffGroupResult[] = []
  let groupIndex = 0

  for (const group of entry.groups) {
    const eslintRules = collectRulesForGroup(sourceConfigs, group as RuleGroupManifest)

    const sourceRules: Record<string, unknown> = {}
    for (const [ruleName, value] of Object.entries(eslintRules)) {
      const remapped = entry.remapRuleName(ruleName)
      if (!remapped) continue
      sourceRules[remapped] = normalizeRuleValue(value)
    }

    const targetRules = normalizeRules(targetOverrides[groupIndex]?.rules ?? {})

    const allKeys = new Set([...Object.keys(sourceRules), ...Object.keys(targetRules)])
    const added: string[] = []
    const removed: string[] = []
    const changed: string[] = []

    for (const key of allKeys) {
      const source = JSON.stringify(sourceRules[key])
      const target = JSON.stringify(targetRules[key])

      if (source === target) continue

      if (key in targetRules && key in sourceRules) {
        changed.push(key)
      } else if (key in targetRules) {
        removed.push(key)
      } else {
        added.push(key)
      }
    }

    results.push({
      groupLabel: group.sourceConfigNames.join('+'),
      added,
      removed,
      changed,
    })

    groupIndex += 1
  }

  return results
}

function printDiffReport(allResults: Array<{ id: string; groups: DiffGroupResult[] }>): boolean {
  let hasDiff = false

  for (const { id, groups } of allResults) {
    for (const group of groups) {
      if (group.added.length === 0 && group.removed.length === 0 && group.changed.length === 0) {
        console.log(`${id}/${group.groupLabel}: in sync`)
        continue
      }

      hasDiff = true
      console.log(`${id}/${group.groupLabel}:`)
      for (const r of group.added) {
        console.log(`  + ${r}`)
      }
      for (const r of group.removed) {
        console.log(`  - ${r}`)
      }
      for (const r of group.changed) {
        console.log(`  ~ ${r}`)
      }
    }
  }

  if (!hasDiff) {
    console.log('All configs are in sync.')
  }

  return hasDiff
}

async function main() {
  const report = process.argv.includes('--report')
  const diff = process.argv.includes('--diff')
  const check = process.argv.includes('--check')

  if (report) {
    const supportedRules = buildSupportedRuleLookup(readRulesFromCommand())
    const reports = await generateMigrationReport(supportedRules)
    printMigrationReport(reports)

    if (process.argv.includes('--write')) {
      await updateReadmeReport(supportedRules)
    }

    return
  }

  if (diff) {
    const rules = readRulesFromCommand()
    const supportedRules = buildSupportedRuleLookup(rules)
    const defaultEnabledRules = buildDefaultEnabledRuleLookup(rules)
    const autoResults = await Promise.all(
      PRESET_MANIFEST.map(async (entry) => ({
        id: entry.id,
        groups: await diffPreset(entry, supportedRules, defaultEnabledRules),
      })),
    )
    const manualResults = await Promise.all(
      MANUAL_DIFF_MANIFEST.map(async (entry) => ({
        id: entry.id,
        groups: await diffManualEntry(entry),
      })),
    )
    const hasDiff = printDiffReport([...autoResults, ...manualResults])
    if (hasDiff) process.exitCode = 1
    return
  }

  const result = await syncOxlintEslint({ check })

  if (check && result.staleFilePaths.length > 0) {
    console.error('Oxlint preset files are out of sync:')

    for (const filePath of result.staleFilePaths) {
      console.error(`- ${path.relative(ROOT_DIR, filePath)}`)
    }

    process.exitCode = 1
    return
  }

  if (check) {
    console.log('Oxlint preset files are in sync.')
    return
  }

  if (result.updatedFilePaths.length === 0) {
    console.log('Oxlint preset files are already up to date.')
    return
  }

  console.log(`Updated ${result.updatedFilePaths.length} Oxlint preset file(s):`)

  for (const filePath of result.updatedFilePaths) {
    console.log(`- ${path.relative(ROOT_DIR, filePath)}`)
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main()
}
