name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run lint
        run: pnpm lint

      - name: Run type check
        run: pnpm typecheck

      - name: Run format check
        run: pnpm format:check

      - name: Run Knip
        run: pnpm knip

      - name: Run spell check
        run: pnpm lint:spell

      - name: Run sync check
        run: pnpm sync:check

      - name: Run tests
        run: pnpm test
